from typing import Any, Optional

from django.forms import Media


class DynamicParlerStyleMixin:
    """
    Mixin that injects the dynamic CSS file into the admin media.
    The CSS file is generated by a view (`admin_dynamic_parler_css_view`)
    that reads the current settings.PARLER_LANGUAGES to apply custom styling
    to language tabs.
    """

    @property
    def media(self):
        """
        Injects the dynamic CSS link after the base admin media.
        """
        media = super().media
        return media + Media(css={"all": ("/admin/dynamic-parler-fixes.css",)})


class AutomatedTranslationMixin:
    """
    Mixin for ModelAdmin classes that automatically triggers GPT translations.
    Requires 'translation_service_method' to be defined (e.g., 'translate_astro_image').
    """

    translation_service_method: Optional[str] = None
    translation_trigger_fields: list[str] = ["name"]

    def save_model(self, request: Any, obj: Any, form: Any, change: bool) -> None:
        """
        Overrides save_model to trigger translations if trigger fields changed.
        """
        super().save_model(request, obj, form, change)

        if not self.translation_service_method:
            return

        # Trigger if new object OR if any trigger field changed
        # We now default to True to allow retrying missing translations
        # (Service handles idempotency)
        should_trigger = True

        # Original logic:
        # should_trigger = not change or any(
        #     field in form.changed_data for field in self.translation_trigger_fields
        # )
        if should_trigger:
            from core.services import TranslationService

            kwargs = self.get_translation_kwargs(obj, form, change, should_trigger)
            TranslationService.trigger_sync(obj, self.translation_service_method, **kwargs)

    def get_translation_kwargs(
        self, obj: Any, form: Any, change: bool, should_trigger: bool
    ) -> dict[str, Any]:
        """
        Hook to provide extra arguments to the translation service method.
        """
        return {}


class TranslationStatusMixin:
    """
    Mixin to add translation status column to admin list views.
    Use alongside AutomatedTranslationMixin.
    """

    def get_list_display(self, request: Any) -> list[str]:
        """Add translation_status to list_display if not already present."""
        list_display = super().get_list_display(request)
        if "translation_status" not in list_display:
            return list(list_display) + ["translation_status"]
        return list(list_display)

    def translation_status(self, obj: Any) -> str:
        """Show aggregated status for all language tasks."""
        from django.contrib.contenttypes.models import ContentType
        from django.utils.safestring import mark_safe

        from core.models import TranslationTask

        tasks = TranslationTask.objects.filter(
            content_type=ContentType.objects.get_for_model(obj), object_id=str(obj.pk)
        )

        if not tasks.exists():
            return mark_safe('<span style="color:gray">➖ Not Started</span>')

        statuses = list(tasks.values_list("status", flat=True))
        failed_count = statuses.count(TranslationTask.Status.FAILED)
        pending_running = sum(
            1
            for s in statuses
            if s in [TranslationTask.Status.PENDING, TranslationTask.Status.RUNNING]
        )

        if failed_count > 0:
            return mark_safe(
                f'<span style="color:red" title="{failed_count} failed">'
                f"❌ Failed ({failed_count})</span>"
            )
        elif pending_running > 0:
            return mark_safe(
                f'<span style="color:orange" title="{pending_running} in progress">'
                f"⏳ In Progress ({pending_running})</span>"
            )
        elif all(s == TranslationTask.Status.COMPLETED for s in statuses):
            return mark_safe(
                f'<span style="color:green" title="{len(statuses)} completed">✅ Complete</span>'
            )

        return mark_safe('<span style="color:gray">➖ Unknown</span>')

    translation_status.short_description = "Translation Status"
