"""
Common mixins for the core application and admin customizations.
"""

from django.conf import settings  # noqa: F401
from django.forms import Media


class DynamicParlerStyleMixin:
    """
    Mixin that injects the dynamic CSS file into the admin media.
    The CSS file is generated by a view (`admin_dynamic_parler_css_view`)
    that reads the current settings.PARLER_LANGUAGES to apply custom styling
    to language tabs.
    """

    @property
    def media(self):
        """
        Injects the dynamic CSS link after the base admin media.
        """
        media = super().media
        return media + Media(css={"all": ("/admin/dynamic-parler-fixes.css",)})
