# Generated by Django 6.0.1 on 2026-01-23 20:21

import uuid

import django_ckeditor_5.fields
import parler.models

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("technologies", models.TextField()),
                ("github_url", models.URLField(blank=True)),
                ("live_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "path",
                    models.ImageField(
                        help_text="The actual image file to be displayed.",
                        upload_to="images/",
                        verbose_name="Image File",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A descriptive name for this image.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Optional detailed description of the image.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="thumbnails/",
                        verbose_name="Thumbnail",
                    ),
                ),
                ("is_cover", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="programming.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Image",
                "verbose_name_plural": "Project Images",
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
