# Generated by Django 5.2.10 on 2026-01-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programming", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammingPageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Programming Page Configuration",
                "verbose_name_plural": "Programming Page Configuration",
            },
        ),
    ]
