# Generated by Django 6.0.1 on 2026-02-03 00:14

import django.db.models.deletion
import django_ckeditor_5.fields
import parler.fields
import parler.models
from django.db import migrations, models



def migrate_translations(apps, schema_editor):
    from django.conf import settings
    default_lang = settings.LANGUAGE_CODE

    ProjectImage = apps.get_model("programming", "ProjectImage")
    ProjectImageTranslation = apps.get_model("programming", "ProjectImageTranslation")

    for obj in ProjectImage.objects.all():
        ProjectImageTranslation.objects.create(
            master_id=obj.pk,
            language_code=default_lang,
            name=obj.name_old,
            description=obj.description_old
        )

class Migration(migrations.Migration):

    dependencies = [
        ("programming", "0001_initial"),
    ]

    operations = [
        # 1. Rename Fields to avoid collision
        migrations.RenameField(
            model_name="projectimage",
            old_name="name",
            new_name="name_old",
        ),
        migrations.RenameField(
            model_name="projectimage",
            old_name="description",
            new_name="description_old",
        ),

        # 2. Create Translation Model
        migrations.CreateModel(
            name="ProjectImageTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A descriptive name for this image.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Optional detailed description of the image.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="programming.projectimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Image Translation",
                "db_table": "programming_projectimage_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        
        # 3. Data Migration
        migrations.RunPython(migrate_translations),

        # 4. Remove Fields
        migrations.RemoveField(
            model_name="projectimage",
            name="description_old",
        ),
        migrations.RemoveField(
            model_name="projectimage",
            name="name_old",
        ),
    ]
