# Generated by Django 6.0.1 on 2026-01-16 20:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programming", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional detailed description of the image.",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="name",
            field=models.CharField(
                help_text="A descriptive name for this image.", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="path",
            field=models.ImageField(
                help_text="The actual image file to be displayed.",
                upload_to="images/",
                verbose_name="Image File",
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
