# Generated by Django 6.0.2 on 2026-02-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programming", "0002_remove_projectimage_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimagetranslation",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="A descriptive name for this image.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
    ]
