# Generated by Django 6.0.1 on 2026-01-16 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programming", "0002_alter_projectimage_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProgrammingPageConfig",
        ),
    ]
