# Generated by Django 6.0.1 on 2026-01-21 13:33

import django_ckeditor_5.fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programming", "0003_delete_programmingpageconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Optional detailed description of the image.",
                verbose_name="Description",
            ),
        ),
    ]
