# Generated by Django 6.0.2 on 2026-03-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programming", "0004_projectimage_legacy_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="legacy_path",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Original file path before WebP conversion. Used for rollback via the Admin serve_webp_images toggle. TODO:Will be removed in future versions.",
                null=True,
                upload_to="images/",
                verbose_name="Legacy Image Path",
            ),
        ),
    ]
