# Generated by Django 6.0.2 on 2026-03-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programming", "0006_rename_legacy_path_original_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="original_image",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Original file path before WebP conversion. Used for rollback via the Admin serve_webp_images toggle. ",
                null=True,
                upload_to="images/",
                verbose_name="Original Image",
            ),
        ),
    ]
