# Generated by Django 6.0.3 on 2026-04-22 18:10

import django.db.models
from django.db import migrations

import common.utils.image


class Migration(migrations.Migration):

    dependencies = [
        ("programming", "0009_alter_projectimage_original_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="original",
            field=django.db.models.ImageField(
                blank=True,
                editable=False,
                help_text="Uploaded source image.",
                null=True,
                upload_to=common.utils.image.SeededImageUploadTo("base_upload_dir", "original"),
                verbose_name="Original Image Source",
            ),
        ),
        migrations.RemoveField(
            model_name="projectimage",
            name="original_image",
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="original_webp",
            field=django.db.models.ImageField(
                blank=True,
                editable=False,
                help_text="Derived WebP image.",
                null=True,
                upload_to=common.utils.image.SeededImageUploadTo("base_upload_dir", "webp"),
                verbose_name="Original Image WebP",
            ),
        ),
        migrations.RemoveField(
            model_name="projectimage",
            name="path",
        ),
    ]
