# Generated by Django 6.0.5 on 2026-06-20 21:53

from django.db import migrations, models

import common.utils.image


class Migration(migrations.Migration):

    dependencies = [
        ("programming", "0009_alter_projectimage_original_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectimage",
            name="original_image",
        ),
        migrations.RemoveField(
            model_name="projectimage",
            name="path",
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="original_webp",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="TODO: Derived WebP image kept during the ImageVariant rollout. Remove after generated variants are the public serving path.",
                null=True,
                upload_to=common.utils.image.SeededImageUploadTo("base_upload_dir", "webp"),
                verbose_name="Original Image WebP",
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="TODO: Legacy thumbnail field kept during the ImageVariant rollout. Remove after thumbnail variants are the public serving path.",
                null=True,
                upload_to=common.utils.image.SeededImageUploadTo("base_upload_dir", "thumbnail"),
                verbose_name="Thumbnail",
            ),
        ),
    ]
