# Generated by Django 6.0.3 on 2026-06-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programming", "0010_remove_projectimage_original_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectimage",
            name="original_webp",
        ),
    ]
