[Definition]
datepattern = "time":"%%Y-%%m-%%dT%%H:%%M:%%S(?:\.%%f)?(?:Z|[+-]%%H:%%M)"
failregex = ^.*"ClientHost":"<HOST>".*"DownstreamStatus":(?:400|401|403).*"RequestHost":"auth\.lukaszremkowicz\.com".*"RequestMethod":"POST".*"RequestPath":"/realms/[^/]+/protocol/openid-connect/token".*$
            ^.*"ClientHost":"<HOST>".*"DownstreamStatus":(?:400|401|403).*"RequestMethod":"POST".*"RequestPath":"/realms/[^/]+/protocol/openid-connect/token".*"RequestHost":"auth\.lukaszremkowicz\.com".*$
ignoreregex =
