# Generated by Django 6.0.3 on 2026-04-11 21:33

import uuid

import django_ckeditor_5.fields
import parler.fields
import parler.models

import django.db.models.deletion
from django.db import migrations, models

import translation.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("astrophotography", "0016_astroimage_calculated_exposure_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "image",
                    models.ImageField(
                        help_text="The source background image used for the shop page.",
                        upload_to="shop/backgrounds/",
                        verbose_name="Background Source",
                    ),
                ),
                (
                    "image_cropped",
                    models.ImageField(
                        blank=True,
                        help_text="Cropped background image managed by the admin image cropper.",
                        null=True,
                        upload_to="shop/backgrounds/",
                        verbose_name="Background Cropped",
                    ),
                ),
                (
                    "image_webp",
                    models.ImageField(
                        blank=True,
                        help_text="Auto-generated WebP version of the background.",
                        null=True,
                        upload_to="shop/backgrounds/",
                        verbose_name="Background WebP",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop Settings",
                "verbose_name_plural": "Shop Settings",
            },
            bases=(
                translation.mixins.AutomatedTranslationModelMixin,
                parler.models.TranslatableModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ShopProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank if price is displayed on the external site.",
                        max_digits=10,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="ISO 4217 currency code, e.g. USD, EUR, PLN.",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "thumbnail_cropped",
                    models.ImageField(
                        blank=True,
                        help_text="Crop of the image specifically meant for the shop list card. Output of the FK cropper.",
                        null=True,
                        upload_to="shop/products/cropped/",
                        verbose_name="Thumbnail (Cropped)",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the product on an external shop or marketplace.",
                        verbose_name="External URL",
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="External CDN URL for the product thumbnail image. Used as a fallback when no local image has been uploaded.",
                        verbose_name="Thumbnail URL",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active products are shown in the public shop.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select an existing gallery image for this product.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrophotography.astroimage",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop Product",
                "verbose_name_plural": "Shop Products",
                "ordering": ["-created_at"],
            },
            bases=(
                translation.mixins.AutomatedTranslationModelMixin,
                parler.models.TranslatableModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ShopProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Product title as displayed in the shop.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Short product description.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="shop.shopproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop Product Translation",
                "db_table": "shop_shopproduct_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ShopSettingsTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Main title displayed on the shop page.",
                        max_length=255,
                        verbose_name="Shop Title",
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Text block displayed below the title.",
                        verbose_name="Shop Description",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="shop.shopsettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop Settings Translation",
                "db_table": "shop_shopsettings_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
