# Generated by Django 6.0.3 on 2026-04-07 09:43

import uuid

import django_ckeditor_5.fields
import parler.fields
import parler.models

import django.db.models.deletion
from django.db import migrations, models

import translation.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "original_image",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        help_text="Original file path before WebP conversion. Used for rollback via the Admin serve_webp_images toggle. ",
                        null=True,
                        upload_to="images/",
                        verbose_name="Original Image",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="thumbnails/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "path",
                    models.ImageField(
                        help_text="The source product image to be displayed.",
                        upload_to="shop/",
                        verbose_name="Product Image",
                    ),
                ),
                (
                    "path_cropped",
                    models.ImageField(
                        blank=True,
                        help_text="Cropped product image managed by the admin image cropper.",
                        null=True,
                        upload_to="shop/",
                        verbose_name="Product Image Cropped",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank if price is displayed on the external site.",
                        max_digits=10,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="ISO 4217 currency code, e.g. USD, EUR, PLN.",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the product on an external shop or marketplace.",
                        verbose_name="External URL",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active products are shown in the public shop.",
                        verbose_name="Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop Product",
                "verbose_name_plural": "Shop Products",
                "ordering": ["-created_at"],
            },
            bases=(
                translation.mixins.AutomatedTranslationModelMixin,
                parler.models.TranslatableModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ShopProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Product title as displayed in the shop.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Short product description.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="shop.shopproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop Product Translation",
                "db_table": "shop_shopproduct_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
