# Generated by Django 6.0.3 on 2026-06-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopproduct",
            name="thumbnail_cropped",
        ),
        migrations.RemoveField(
            model_name="shopsettings",
            name="image_webp",
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="image_cropped",
            field=models.ImageField(
                blank=True,
                db_column="thumbnail_cropped",
                help_text="Crop of the selected original image. Used as the source for generated shop variants.",
                null=True,
                upload_to="shop/products/cropped/",
                verbose_name="Image (Cropped)",
            ),
        ),
    ]
