# Generated by Django 6.0.1 on 2026-02-05 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "task_id",
                    models.CharField(help_text="Celery Task ID", max_length=255, unique=True),
                ),
                (
                    "object_id",
                    models.CharField(
                        help_text="Primary Key of the object (Int or UUID)", max_length=255
                    ),
                ),
                ("language", models.CharField(max_length=10, verbose_name="Target Language")),
                ("method", models.CharField(max_length=100, verbose_name="Translation Method")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Task Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="Error Message"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation Task",
                "verbose_name_plural": "Translation Tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="translation_content_8bc56e_idx"
                    ),
                    models.Index(fields=["status"], name="translation_status_dd9038_idx"),
                ],
            },
        ),
    ]
