# Generated by Django 6.0.2 on 2026-02-10 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("analysis_date", models.DateField(db_index=True, unique=True)),
                ("backend_logs", models.TextField(help_text="Raw backend logs")),
                ("frontend_logs", models.TextField(help_text="Raw frontend logs")),
                ("log_size_bytes", models.IntegerField(default=0)),
                ("summary", models.TextField(help_text="GPT-generated summary")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                (
                    "key_findings",
                    models.JSONField(default=list, help_text="List of important findings"),
                ),
                ("recommendations", models.TextField(blank=True, help_text="GPT recommendations")),
                ("execution_time_seconds", models.FloatField(default=0.0)),
                ("gpt_tokens_used", models.IntegerField(default=0)),
                ("email_sent", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Log Analysis",
                "verbose_name_plural": "Log Analyses",
                "ordering": ["-analysis_date"],
            },
        ),
    ]
