# Generated by Django 6.0.2 on 2026-02-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loganalysis",
            name="backend_logs",
            field=models.FileField(help_text="Raw backend logs", upload_to="logs/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="frontend_logs",
            field=models.FileField(help_text="Raw frontend logs", upload_to="logs/%Y/%m/%d/"),
        ),
    ]
