# Generated by Django 6.0.2 on 2026-02-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_alter_loganalysis_backend_logs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loganalysis",
            name="backend_logs",
            field=models.FileField(
                blank=True, help_text="Raw backend logs", null=True, upload_to="logs/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="frontend_logs",
            field=models.FileField(
                blank=True, help_text="Raw frontend logs", null=True, upload_to="logs/%Y/%m/%d/"
            ),
        ),
    ]
