# Generated by Django 6.0.2 on 2026-03-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_alter_loganalysis_backend_logs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loganalysis",
            name="gpt_cost_usd",
            field=models.FloatField(default=0.0, help_text="Estimated OpenAI API cost in USD"),
        ),
        migrations.AddField(
            model_name="loganalysis",
            name="nginx_logs",
            field=models.FileField(
                blank=True, help_text="Raw nginx logs", null=True, upload_to="logs/%Y/%m/%d/"
            ),
        ),
    ]
