# Generated by Django 6.0.2 on 2026-03-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_loganalysis_gpt_cost_usd_loganalysis_nginx_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="loganalysis",
            name="trend_summary",
            field=models.TextField(
                blank=True, help_text="LLM-generated trend comparison vs. prior days"
            ),
        ),
    ]
