# Generated by Django 6.0.2 on 2026-04-04 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0007_sitemapanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="loganalysis",
            name="fail2ban_logs",
            field=models.FileField(
                blank=True,
                help_text="Raw fail2ban logs",
                null=True,
                upload_to="logs/%Y/%m/%d/",
                verbose_name="Fail2ban logs",
            ),
        ),
        migrations.AddField(
            model_name="loganalysis",
            name="nginx_runtime_logs",
            field=models.FileField(
                blank=True,
                help_text="Raw nginx runtime logs",
                null=True,
                upload_to="logs/%Y/%m/%d/",
                verbose_name="Nginx runtime logs",
            ),
        ),
        migrations.AddField(
            model_name="loganalysis",
            name="traefik_runtime_logs",
            field=models.FileField(
                blank=True,
                help_text="Raw traefik runtime logs",
                null=True,
                upload_to="logs/%Y/%m/%d/",
                verbose_name="Traefik runtime logs",
            ),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="analysis_date",
            field=models.DateField(db_index=True, unique=True, verbose_name="Analysis date"),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="backend_logs",
            field=models.FileField(
                blank=True,
                help_text="Raw backend logs",
                null=True,
                upload_to="logs/%Y/%m/%d/",
                verbose_name="Backend logs",
            ),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="email_sent",
            field=models.BooleanField(default=False, verbose_name="Email sent"),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="Error message"),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="execution_time_seconds",
            field=models.FloatField(default=0.0, verbose_name="Execution time seconds"),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="frontend_logs",
            field=models.FileField(
                blank=True,
                help_text="Raw frontend logs",
                null=True,
                upload_to="logs/%Y/%m/%d/",
                verbose_name="Frontend logs",
            ),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="gpt_cost_usd",
            field=models.FloatField(
                default=0.0,
                help_text="Estimated OpenAI API cost in USD",
                verbose_name="Gpt cost usd",
            ),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="gpt_tokens_used",
            field=models.IntegerField(default=0, verbose_name="Gpt tokens used"),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="key_findings",
            field=models.JSONField(
                default=list, help_text="List of important findings", verbose_name="Key findings"
            ),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="log_size_bytes",
            field=models.IntegerField(default=0, verbose_name="Log Size"),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="nginx_logs",
            field=models.FileField(
                blank=True,
                help_text="Raw nginx logs",
                null=True,
                upload_to="logs/%Y/%m/%d/",
                verbose_name="Nginx logs",
            ),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="recommendations",
            field=models.TextField(
                blank=True, help_text="GPT recommendations", verbose_name="Recommendations"
            ),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="severity",
            field=models.CharField(
                choices=[("INFO", "Info"), ("WARNING", "Warning"), ("CRITICAL", "Critical")],
                default="INFO",
                max_length=10,
                verbose_name="Severity",
            ),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="summary",
            field=models.TextField(help_text="GPT-generated summary", verbose_name="Summary"),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="traefik_logs",
            field=models.FileField(
                blank=True,
                help_text="Raw traefik logs",
                null=True,
                upload_to="logs/%Y/%m/%d/",
                verbose_name="Traefik logs",
            ),
        ),
        migrations.AlterField(
            model_name="loganalysis",
            name="trend_summary",
            field=models.TextField(
                blank=True,
                help_text="LLM-generated trend comparison vs. prior days",
                verbose_name="Trend summary",
            ),
        ),
        migrations.AlterField(
            model_name="sitemapanalysis",
            name="analysis_date",
            field=models.DateField(db_index=True, unique=True, verbose_name="Analysis date"),
        ),
        migrations.AlterField(
            model_name="sitemapanalysis",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="sitemapanalysis",
            name="email_sent",
            field=models.BooleanField(default=False, verbose_name="Email sent"),
        ),
        migrations.AlterField(
            model_name="sitemapanalysis",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="Error message"),
        ),
        migrations.AlterField(
            model_name="sitemapanalysis",
            name="execution_time_seconds",
            field=models.FloatField(default=0.0, verbose_name="Execution time seconds"),
        ),
        migrations.AlterField(
            model_name="sitemapanalysis",
            name="gpt_cost_usd",
            field=models.FloatField(
                default=0.0,
                help_text="Estimated OpenAI API cost in USD",
                verbose_name="GPT cost usd",
            ),
        ),
        migrations.AlterField(
            model_name="sitemapanalysis",
            name="gpt_tokens_used",
            field=models.IntegerField(default=0, verbose_name="GPT tokens used"),
        ),
        migrations.AlterField(
            model_name="sitemapanalysis",
            name="issue_summary",
            field=models.JSONField(
                default=dict,
                help_text="Counts by sitemap issue category",
                verbose_name="Issue summary",
            ),
        ),
        migrations.AlterField(
            model_name="sitemapanalysis",
            name="issues",
            field=models.JSONField(
                default=list,
                help_text="Detailed deterministic sitemap issues",
                verbose_name="Issues",
            ),
        ),
        migrations.AlterField(
            model_name="sitemapanalysis",
            name="key_findings",
            field=models.JSONField(
                default=list,
                help_text="List of important sitemap findings",
                verbose_name="Key findings",
            ),
        ),
        migrations.AlterField(
            model_name="sitemapanalysis",
            name="recommendations",
            field=models.TextField(
                blank=True, help_text="LLM recommendations", verbose_name="Recommendations"
            ),
        ),
        migrations.AlterField(
            model_name="sitemapanalysis",
            name="root_sitemap_url",
            field=models.URLField(verbose_name="Root sitemap URL"),
        ),
        migrations.AlterField(
            model_name="sitemapanalysis",
            name="severity",
            field=models.CharField(
                choices=[("INFO", "Info"), ("WARNING", "Warning"), ("CRITICAL", "Critical")],
                default="INFO",
                max_length=10,
                verbose_name="Severity",
            ),
        ),
        migrations.AlterField(
            model_name="sitemapanalysis",
            name="summary",
            field=models.TextField(
                help_text="LLM-generated sitemap summary", verbose_name="Summary"
            ),
        ),
        migrations.AlterField(
            model_name="sitemapanalysis",
            name="total_sitemaps",
            field=models.IntegerField(default=0, verbose_name="Total sitemaps"),
        ),
        migrations.AlterField(
            model_name="sitemapanalysis",
            name="total_urls",
            field=models.IntegerField(default=0, verbose_name="Total urls"),
        ),
        migrations.AlterField(
            model_name="sitemapanalysis",
            name="trend_summary",
            field=models.TextField(
                blank=True,
                help_text="Sitemap trend comparison summary",
                verbose_name="Trend summary",
            ),
        ),
    ]
