# Generated by Django 6.0.5 on 2026-06-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0008_loganalysis_fail2ban_logs_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LogAnalysis",
        ),
        migrations.DeleteModel(
            name="SitemapAnalysis",
        ),
    ]
