# Generated by Django 6.0.1
import uuid

import django_ckeditor_5.fields
import django_countries.fields
import parler.fields
import parler.models

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models

import astrophotography.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="",
                        help_text="The model identifiers or name of the equipment.",
                        max_length=255,
                        verbose_name="Model",
                    ),
                ),
            ],
            options={"verbose_name": "Camera", "verbose_name_plural": "Cameras"},
        ),
        migrations.CreateModel(
            name="Lens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="",
                        help_text="The model identifiers or name of the equipment.",
                        max_length=255,
                        verbose_name="Model",
                    ),
                ),
            ],
            options={"verbose_name": "Lens", "verbose_name_plural": "Lenses"},
        ),
        migrations.CreateModel(
            name="MainPageBackgroundImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="thumbnails/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "path",
                    models.ImageField(
                        help_text="The large background image file.",
                        upload_to="backgrounds/",
                        verbose_name="Image File",
                    ),
                ),
            ],
            options={
                "verbose_name": "Main Page Background Image",
                "verbose_name_plural": "Main Page Background Images",
                "ordering": ["-created_at"],
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name="MeteorsMainPageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "random_stars_shooting",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, shooting stars will have randomized flight angles (0-360°). If disabled, they will follow a fixed -45° diagonal path.",
                        verbose_name="Random Shooting Stars",
                    ),
                ),
                (
                    "bolid_chance",
                    models.FloatField(
                        default=0.1,
                        help_text="The probability (0.0 to 1.0) of a regular shooting star being a 'bolid' (fireball). 0.1 means a 10% chance.",
                        verbose_name="Bolid Chance",
                    ),
                ),
                (
                    "bolid_interval",
                    models.IntegerField(
                        default=60,
                        help_text="The minimum wait time (in seconds) between two bolid spawns to prevent cluster sightings. Duration ranges (in seconds) on screen depends on path distance. Speed = PathDistance / Duration. - Smaller duration + Larger distance = High speed. - Larger duration + Smaller distance = Low speed.",
                        verbose_name="Bolid Minimum Interval",
                    ),
                ),
                (
                    "star_path_range",
                    models.JSONField(
                        default=astrophotography.models.default_star_path,
                        help_text="A list of two integers [min, max] representing the travel distance of a regular star in pixels. Example: [50, 500]",
                        verbose_name="Star Path Range (px)",
                    ),
                ),
                (
                    "bolid_path_range",
                    models.JSONField(
                        default=astrophotography.models.default_bolid_path,
                        help_text="A list of two integers [min, max] representing the travel distance of a bolid in pixels. Example: [50, 500]",
                        verbose_name="Bolid Path Range (px)",
                    ),
                ),
                (
                    "star_streak_range",
                    models.JSONField(
                        default=astrophotography.models.default_star_streak,
                        help_text="A list of two integers [min, max] representing the visual length (streak) of a regular star. Example: [100, 200]",
                        verbose_name="Star Streak Range (px)",
                    ),
                ),
                (
                    "bolid_streak_range",
                    models.JSONField(
                        default=astrophotography.models.default_bolid_streak,
                        help_text="A list of two integers [min, max] representing the visual length (streak) of a bolid. Example: [20, 100]",
                        verbose_name="Bolid Streak Range (px)",
                    ),
                ),
                (
                    "star_duration_range",
                    models.JSONField(
                        default=astrophotography.models.default_star_duration,
                        help_text="A list of two floats [min, max] representing the duration (speed) of a regular star. Example: [0.4, 1.2]",
                        verbose_name="Star Duration Range (s)",
                    ),
                ),
                (
                    "bolid_duration_range",
                    models.JSONField(
                        default=astrophotography.models.default_bolid_duration,
                        help_text="A list of two floats [min, max] representing the duration (speed) of a bolid. Example: [0.4, 0.9]",
                        verbose_name="Bolid Duration Range (s)",
                    ),
                ),
                (
                    "star_opacity_range",
                    models.JSONField(
                        default=astrophotography.models.default_star_opacity,
                        help_text="A list of two floats [min, max] between 0.0 and 1.0 for regular star brightness. Example: [0.4, 0.8]",
                        verbose_name="Star Opacity Range",
                    ),
                ),
                (
                    "bolid_opacity_range",
                    models.JSONField(
                        default=astrophotography.models.default_bolid_opacity,
                        help_text="A list of two floats [min, max] between 0.0 and 1.0 for bolid brightness. Example: [0.7, 1.0]",
                        verbose_name="Bolid Opacity Range",
                    ),
                ),
                (
                    "smoke_opacity_range",
                    models.JSONField(
                        default=astrophotography.models.default_smoke_opacity,
                        help_text="A list of two floats [min, max] between 0.0 and 1.0 for the smoke trail of a bolid. Example: [0.5, 0.8]",
                        verbose_name="Smoke Opacity Range",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Meteors Main Page Configuration",
                "verbose_name_plural": "Meteors Main Page Configuration",
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(max_length=2, verbose_name="Country"),
                ),
            ],
            options={
                "verbose_name": "Place",
                "verbose_name_plural": "Places",
                "ordering": ["translations__name"],
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags"},
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name="Telescope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="",
                        help_text="The model identifiers or name of the equipment.",
                        max_length=255,
                        verbose_name="Model",
                    ),
                ),
            ],
            options={"verbose_name": "Telescope", "verbose_name_plural": "Telescopes"},
        ),
        migrations.CreateModel(
            name="Tracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="",
                        help_text="The model identifiers or name of the equipment.",
                        max_length=255,
                        verbose_name="Model",
                    ),
                ),
            ],
            options={"verbose_name": "Tracker", "verbose_name_plural": "Trackers"},
        ),
        migrations.CreateModel(
            name="Tripod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="",
                        help_text="The model identifiers or name of the equipment.",
                        max_length=255,
                        verbose_name="Model",
                    ),
                ),
            ],
            options={"verbose_name": "Tripod", "verbose_name_plural": "Tripods"},
        ),
        migrations.CreateModel(
            name="AstroImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "path",
                    models.ImageField(
                        help_text="The actual image file to be displayed.",
                        upload_to="images/",
                        verbose_name="Image File",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="thumbnails/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "capture_date",
                    models.DateField(
                        help_text="The date when the photo was taken.", verbose_name="Capture Date"
                    ),
                ),
                (
                    "celestial_object",
                    models.CharField(
                        choices=[
                            ("Landscape", "Landscape"),
                            ("Deep Sky", "Deep Sky"),
                            ("Startrails", "Startrails"),
                            ("Solar System", "Solar System"),
                            ("Milky Way", "Milky Way"),
                            ("Northern Lights", "Northern Lights"),
                        ],
                        help_text="The type of celestial object captured.",
                        max_length=50,
                        verbose_name="Celestial Object",
                    ),
                ),
                (
                    "astrobin_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to this image on Astrobin (e.g., https://www.astrobin.com/XXXXX/)",
                        verbose_name="Astrobin URL",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="SEO friendly URL slug.",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "zoom",
                    models.BooleanField(
                        default=False,
                        help_text="Allow users to zoom this image in detail mode.",
                        verbose_name="Zoom",
                    ),
                ),
                (
                    "camera",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Camera model and specifications",
                        to="astrophotography.camera",
                        verbose_name="Camera",
                    ),
                ),
                (
                    "lens",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Lens model and focal length",
                        to="astrophotography.lens",
                        verbose_name="Lens",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific city or region (e.g. Hawaii, Tenerife).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrophotography.place",
                        verbose_name="Place/City",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="images",
                        to="astrophotography.tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "telescope",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Telescope model and specifications",
                        to="astrophotography.telescope",
                        verbose_name="Telescope",
                    ),
                ),
                (
                    "tracker",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Star tracker or mount model",
                        to="astrophotography.tracker",
                        verbose_name="Tracker/Mount",
                    ),
                ),
                (
                    "tripod",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tripod model",
                        to="astrophotography.tripod",
                        verbose_name="Tripod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Astrophotography Image",
                "verbose_name_plural": "Astrophotography Images",
                "ordering": ["-created_at"],
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name="MainPageLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Toggle visibility on the homepage.",
                        verbose_name="Is Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "adventure_date",
                    django.contrib.postgres.fields.ranges.DateRangeField(
                        blank=True,
                        help_text="The date range of the expedition.",
                        null=True,
                        verbose_name="Adventure Date Range",
                    ),
                ),
                (
                    "country_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-generated slug for the country.",
                        max_length=100,
                        verbose_name="Country Slug",
                    ),
                ),
                (
                    "place_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-generated slug for the place.",
                        max_length=100,
                        null=True,
                        verbose_name="Place Slug",
                    ),
                ),
                (
                    "background_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional specific background image for this location's page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="location_backgrounds",
                        to="astrophotography.astroimage",
                        verbose_name="Background Image",
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select images to display in the slideshow for this location (filtered by country).",
                        related_name="location_sliders",
                        to="astrophotography.astroimage",
                        verbose_name="Images",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific city or region (e.g. Hawaii, Tenerife)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrophotography.place",
                        verbose_name="Place/City",
                    ),
                ),
            ],
            options={
                "verbose_name": "Main Page Location",
                "verbose_name_plural": "Main Page Locations",
                "ordering": ["-adventure_date"],
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name="TagTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=100, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="astrophotography.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag Translation",
                "db_table": "astrophotography_tag_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
        ),
        migrations.CreateModel(
            name="PlaceTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Name")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="astrophotography.place",
                    ),
                ),
            ],
            options={
                "verbose_name": "Place Translation",
                "db_table": "astrophotography_place_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
        ),
        migrations.CreateModel(
            name="MainPageLocationTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                (
                    "highlight_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom name for the travel highlight (overrides Country/Place).",
                        max_length=100,
                        null=True,
                        verbose_name="Highlight Name",
                    ),
                ),
                (
                    "story",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Optional story or blog text to display above the images.",
                        null=True,
                        verbose_name="Story/Blog Text",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="astrophotography.mainpagelocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Main Page Location Translation",
                "db_table": "astrophotography_mainpagelocation_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
        ),
        migrations.CreateModel(
            name="MainPageBackgroundImageTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                (
                    "name",
                    models.CharField(
                        default="Background Image",
                        help_text="Identifier for the background image.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Optional detailed description of the image.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="astrophotography.mainpagebackgroundimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Main Page Background Image Translation",
                "db_table": "astrophotography_mainpagebackgroundimage_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
        ),
        migrations.CreateModel(
            name="AstroImageTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A descriptive name for this image.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Optional detailed description of the image.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "exposure_details",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Technical details of the exposure (gain, sub-exposures, total time).",
                        verbose_name="Exposure Details",
                    ),
                ),
                (
                    "processing_details",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Software and techniques used for post-processing.",
                        verbose_name="Processing Details",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="astrophotography.astroimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Astrophotography Image Translation",
                "db_table": "astrophotography_astroimage_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
        ),
    ]
