# Generated by Django 6.0.1 on 2026-01-13 21:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AstroImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("path", models.ImageField(upload_to="images/")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("capture_date", models.DateField()),
                ("location", models.CharField(max_length=255)),
                ("equipment", models.TextField(blank=True)),
                ("exposure_details", models.TextField(blank=True)),
                ("processing_details", models.TextField(blank=True)),
                (
                    "celestial_object",
                    models.CharField(
                        choices=[
                            ("Landscape", "Landscape"),
                            ("Deep Sky", "Deep Sky"),
                            ("Startrails", "Startrails"),
                            ("Solar System", "Solar System"),
                            ("Milky Way", "Milky Way"),
                            ("Northern Lights", "Northern Lights"),
                        ]
                    ),
                ),
                (
                    "astrobin_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to this image on Astrobin (e.g., https://www.astrobin.com/XXXXX/)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Astrophotography Image",
                "verbose_name_plural": "Astrophotography Images",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BackgroundMainPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
                ("name", models.CharField(default="Background Image", max_length=255)),
                ("path", models.ImageField(upload_to="backgrounds/")),
            ],
            options={
                "verbose_name": "Background Main Page",
                "verbose_name_plural": "Background Main Pages",
                "ordering": ["-created_at"],
            },
        ),
    ]
