# Generated by Django 5.2.3 on 2025-06-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrophotography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='backgrounds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
