# Generated by Django 6.0.1 on 2026-01-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="astroimage",
            name="thumbnail",
            field=models.ImageField(blank=True, editable=False, null=True, upload_to="thumbnails/"),
        ),
    ]
