# Generated by Django 6.0.1 on 2026-01-25 00:24

from django.db import migrations, models

import astrophotography.models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0001_initial"),
    ]

    operations = [
        # 1. Celestial Object adjustment (from old 0002)
        migrations.AlterField(
            model_name="astroimage",
            name="celestial_object",
            field=models.CharField(
                choices=[
                    ("Landscape", "Landscape"),
                    ("Deep Sky", "Deep Sky"),
                    ("Startrails", "Startrails"),
                    ("Solar System", "Solar System"),
                    ("Milky Way", "Milky Way"),
                    ("Northern Lights", "Northern Lights"),
                ],
                help_text="The type of celestial object captured.",
                max_length=50,
                verbose_name="Celestial Object",
            ),
        ),
        # 2. Meteors Configuration (from old 0003, 0004, 0005)
        migrations.CreateModel(
            name="MeteorsMainPageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "random_stars_shooting",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, shooting stars will have randomized flight angles (0-360°). If disabled, they will follow a fixed -45° diagonal path.",
                        verbose_name="Random Shooting Stars",
                    ),
                ),
                (
                    "bolid_chance",
                    models.FloatField(
                        default=0.1,
                        help_text="The probability (0.0 to 1.0) of a regular shooting star being a 'bolid' (fireball). 0.1 means a 10% chance.",
                        verbose_name="Bolid Chance",
                    ),
                ),
                (
                    "bolid_interval",
                    models.IntegerField(
                        default=60,
                        help_text="The minimum wait time (in seconds) between two bolid spawns to prevent cluster sightings.",
                        verbose_name="Bolid Minimum Interval",
                    ),
                ),
                (
                    "star_path_range",
                    models.JSONField(
                        default=astrophotography.models.default_star_path,
                        help_text="A list of two integers [min, max] representing the travel distance of a regular star in pixels.",
                        verbose_name="Star Path Range (px)",
                    ),
                ),
                (
                    "bolid_path_range",
                    models.JSONField(
                        default=astrophotography.models.default_bolid_path,
                        help_text="A list of two integers [min, max] representing the travel distance of a bolid in pixels.",
                        verbose_name="Bolid Path Range (px)",
                    ),
                ),
                (
                    "star_streak_range",
                    models.JSONField(
                        default=astrophotography.models.default_star_streak,
                        help_text="A list of two integers [min, max] representing the visual length (streak) of a regular star.",
                        verbose_name="Star Streak Range (px)",
                    ),
                ),
                (
                    "bolid_streak_range",
                    models.JSONField(
                        default=astrophotography.models.default_bolid_streak,
                        help_text="A list of two integers [min, max] representing the visual length (streak) of a bolid.",
                        verbose_name="Bolid Streak Range (px)",
                    ),
                ),
                (
                    "star_duration_range",
                    models.JSONField(
                        default=astrophotography.models.default_star_duration,
                        help_text="A list of two floats [min, max] representing the duration (speed) of a regular star.",
                        verbose_name="Star Duration Range (s)",
                    ),
                ),
                (
                    "bolid_duration_range",
                    models.JSONField(
                        default=astrophotography.models.default_bolid_duration,
                        help_text="A list of two floats [min, max] representing the duration (speed) of a bolid.",
                        verbose_name="Bolid Duration Range (s)",
                    ),
                ),
                (
                    "star_opacity_range",
                    models.JSONField(
                        default=astrophotography.models.default_star_opacity,
                        help_text="A list of two floats [min, max] between 0.0 and 1.0 for regular star brightness.",
                        verbose_name="Star Opacity Range",
                    ),
                ),
                (
                    "bolid_opacity_range",
                    models.JSONField(
                        default=astrophotography.models.default_bolid_opacity,
                        help_text="A list of two floats [min, max] between 0.0 and 1.0 for bolid brightness.",
                        verbose_name="Bolid Opacity Range",
                    ),
                ),
                (
                    "smoke_opacity_range",
                    models.JSONField(
                        default=astrophotography.models.default_smoke_opacity,
                        help_text="A list of two floats [min, max] between 0.0 and 1.0 for the smoke trail of a bolid.",
                        verbose_name="Smoke Opacity Range",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Meteors Main Page Configuration",
                "verbose_name_plural": "Meteors Main Page Configuration",
            },
        ),
        # 3. Equipment Metadata Cleanup (from old 0006-0012)
        migrations.AlterModelOptions(
            name="camera",
            options={"verbose_name": "Camera", "verbose_name_plural": "Cameras"},
        ),
        migrations.AlterModelOptions(
            name="lens",
            options={"verbose_name": "Lens", "verbose_name_plural": "Lenses"},
        ),
        migrations.AlterModelOptions(
            name="telescope",
            options={"verbose_name": "Telescope", "verbose_name_plural": "Telescopes"},
        ),
        migrations.AlterModelOptions(
            name="tracker",
            options={"verbose_name": "Tracker", "verbose_name_plural": "Trackers"},
        ),
        migrations.AlterModelOptions(
            name="tripod",
            options={"verbose_name": "Tripod", "verbose_name_plural": "Tripods"},
        ),
        migrations.AlterModelOptions(
            name="place",
            options={"verbose_name": "Place", "verbose_name_plural": "Places"},
        ),
        migrations.RemoveField(
            model_name="tracker",
            name="name",
        ),
        migrations.RemoveField(
            model_name="tripod",
            name="name",
        ),
        migrations.AddField(
            model_name="tracker",
            name="model",
            field=models.CharField(
                default="",
                help_text="The model identifiers or name of the equipment.",
                max_length=255,
                verbose_name="Model",
            ),
        ),
        migrations.AddField(
            model_name="tripod",
            name="model",
            field=models.CharField(
                default="",
                help_text="The model identifiers or name of the equipment.",
                max_length=255,
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="model",
            field=models.CharField(
                default="",
                help_text="The model identifiers or name of the equipment.",
                max_length=255,
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="lens",
            name="model",
            field=models.CharField(
                default="",
                help_text="The model identifiers or name of the equipment.",
                max_length=255,
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="telescope",
            name="model",
            field=models.CharField(
                default="",
                help_text="The model identifiers or name of the equipment.",
                max_length=255,
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(
                default="",
                help_text="The name of the specific place or city.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        # 4. SEO Slugs for AstroImage (from old 0013-0015)
        migrations.AddField(
            model_name="astroimage",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="SEO friendly URL slug.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
