# Generated by Django 6.0.1
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- 1. Idempotent Rename of taggit_tag to astrophotography_tag
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'taggit_tag')
                   AND NOT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'astrophotography_tag') THEN
                    ALTER TABLE taggit_tag RENAME TO astrophotography_tag;
                END IF;
            END $$;

            -- 2. Ensure Name and Slug types are consistent if we just renamed
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'astrophotography_tag' AND column_name = 'name') THEN
                    ALTER TABLE astrophotography_tag ALTER COLUMN name TYPE VARCHAR(100);
                END IF;
                IF EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'astrophotography_tag' AND column_name = 'slug') THEN
                    ALTER TABLE astrophotography_tag ALTER COLUMN slug TYPE VARCHAR(100);
                END IF;
            END $$;

            -- 3. Ensure destination column exists in translation table
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'astrophotography_tag_translation' AND column_name = 'slug') THEN
                    ALTER TABLE astrophotography_tag_translation ADD COLUMN slug VARCHAR(100);
                    -- We'll add UNIQUE later or keep it as-is if it's the first population
                END IF;
            END $$;

            -- 4. Populate Translations from renamed columns
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'astrophotography_tag' AND column_name = 'name')
                   AND EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'astrophotography_tag_translation') THEN

                    INSERT INTO astrophotography_tag_translation (language_code, master_id, name, slug)
                    SELECT 'en', id, COALESCE(name, 'Tag ' || id), slug
                    FROM astrophotography_tag
                    ON CONFLICT (language_code, master_id) DO NOTHING;

                    -- Only drop if we successfully populated some translations
                    IF EXISTS (SELECT 1 FROM astrophotography_tag_translation) THEN
                        ALTER TABLE astrophotography_tag DROP COLUMN name;
                        ALTER TABLE astrophotography_tag DROP COLUMN slug;
                    END IF;
                END IF;
            END $$;

            -- 4. Migrate M2M relations from taggit_taggeditem
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'taggit_taggeditem')
                   AND EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'astrophotography_astroimage_tags') THEN

                    INSERT INTO astrophotography_astroimage_tags (astroimage_id, tag_id)
                    SELECT CAST(object_id AS TEXT)::UUID, tag_id
                    FROM taggit_taggeditem
                    WHERE content_type_id = (SELECT id FROM django_content_type WHERE app_label='astrophotography' AND model='astroimage')
                    ON CONFLICT (astroimage_id, tag_id) DO NOTHING;
                END IF;
            END $$;
            """,
            reverse_sql="SELECT 1;",  # Reversed transitions are complex, usually better to restore from backup
        ),
    ]
