# Generated by Django 6.0.1 on 2026-02-04 20:45

import django_countries.fields
import parler.fields
import parler.models
import taggit.managers

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_tags_from_taggit(apps, schema_editor):
    try:
        TaggitTag = apps.get_model("taggit", "Tag")
    except LookupError:
        return

    Tag = apps.get_model("astrophotography", "Tag")
    TagTranslation = apps.get_model("astrophotography", "TagTranslation")
    default_lang = getattr(settings, "PARLER_DEFAULT_LANGUAGE_CODE", "en")

    print("DEBUG: Executing copy_tags_from_taggit...")

    # We used raw SQL before to handle ID preservation safely, let's Stick to that
    # but adapt for the new model structure (Tag + TagTranslation).

    # 1. Copy base tags (ID + Slug)
    # We want to preserve IDs so existing relationships (UUIDTaggedItem) remain valid.
    source_table = TaggitTag._meta.db_table
    dest_table = Tag._meta.db_table

    try:
        with schema_editor.connection.cursor() as cursor:
            # Check if source has data
            cursor.execute(f"SELECT count(*) FROM {source_table}")
            if cursor.fetchone()[0] == 0:
                print("DEBUG: Source table empty.")
                return

            print(f"DEBUG: Copying from {source_table} to {dest_table}")
            # Insert into Tag (id, slug, name)
            cursor.execute(
                f"INSERT INTO {dest_table} (id, slug, name) SELECT id, slug, name FROM {source_table} ON CONFLICT DO NOTHING"
            )

            # Reset sequence for Tag
            if schema_editor.connection.vendor == "postgresql":
                cursor.execute(
                    f"SELECT setval(pg_get_serial_sequence('{dest_table}', 'id'), coalesce(max(id),0) + 1, false) FROM {dest_table};"
                )

            # 2. Insert Translations (title)
            # We need to copy 'name' from taggit_tag to 'title' in astrophotography_tag_translation
            dest_trans_table = TagTranslation._meta.db_table

            # We assume 'master_id' is the FK column name to Tag. Parler default.
            # We set language_code to default_lang.
            cursor.execute(
                f"INSERT INTO {dest_trans_table} (language_code, title, master_id) SELECT '{default_lang}', name, id FROM {source_table} ON CONFLICT DO NOTHING"
            )
            print("DEBUG: Copy complete.")
    except Exception as e:
        print(f"DEBUG: Error during copy: {e}")
        # Don't crash migration if copy fails, maybe table exists/empty
        pass


def reverse_copy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=100, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TagTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="astrophotography.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag Translation",
                "db_table": "astrophotography_tag_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RunPython(copy_tags_from_taggit, reverse_copy),
        migrations.AlterModelOptions(
            name="mainpagebackgroundimage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Main Page Background Image",
                "verbose_name_plural": "Main Page Background Images",
            },
        ),
        migrations.AlterModelOptions(
            name="mainpagebackgroundimagetranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Main Page Background Image Translation",
            },
        ),
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["translations__name"],
                "verbose_name": "Place",
                "verbose_name_plural": "Places",
            },
        ),
        migrations.AlterModelOptions(
            name="uuidtaggeditem",
            options={"verbose_name": "Tagged Item", "verbose_name_plural": "Tagged Items"},
        ),
        migrations.AlterField(
            model_name="mainpagebackgroundimagetranslation",
            name="name",
            field=models.CharField(
                default="Background Image",
                help_text="Identifier for the background image.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="country",
            field=django_countries.fields.CountryField(max_length=2, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="placetranslation",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="Relevant tags for the image.",
                through="astrophotography.UUIDTaggedItem",
                to="astrophotography.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="uuidtaggeditem",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="astrophotography.tag",
                verbose_name="Tag",
            ),
        ),
    ]
