# Generated by Django 5.2.3 on 2025-06-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrophotography', '0002_backgroundmainpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astroimage',
            name='celestial_object',
            field=models.CharField(choices=[('Landscape', 'Landscape'), ('Deep Sky', 'Deep Sky'), ('Startrails', 'Startrails'), ('Solar System', 'Solar System'), ('Milky Way', 'Milky Way'), ('Northern Lights', 'Northern Lights')]),
        ),
    ]
