# Generated by Django 6.0.1 on 2026-01-28 21:15

from django.db import migrations, models

import astrophotography.models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0002_consolidated_updates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["name"],
                "verbose_name": "Place",
                "verbose_name_plural": "Places",
            },
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="SEO friendly URL slug.",
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="meteorsmainpageconfig",
            name="bolid_duration_range",
            field=models.JSONField(
                default=astrophotography.models.default_bolid_duration,
                help_text="A list of two floats [min, max] representing the duration (speed) of a bolid. Example: [0.4, 0.9]",
                verbose_name="Bolid Duration Range (s)",
            ),
        ),
        migrations.AlterField(
            model_name="meteorsmainpageconfig",
            name="bolid_interval",
            field=models.IntegerField(
                default=60,
                help_text="The minimum wait time (in seconds) between two bolid spawns to prevent cluster sightings. Duration ranges (in seconds) on screen depends on path distance. Speed = PathDistance / Duration. - Smaller duration + Larger distance = High speed. - Larger duration + Smaller distance = Low speed.",
                verbose_name="Bolid Minimum Interval",
            ),
        ),
        migrations.AlterField(
            model_name="meteorsmainpageconfig",
            name="bolid_opacity_range",
            field=models.JSONField(
                default=astrophotography.models.default_bolid_opacity,
                help_text="A list of two floats [min, max] between 0.0 and 1.0 for bolid brightness. Example: [0.7, 1.0]",
                verbose_name="Bolid Opacity Range",
            ),
        ),
        migrations.AlterField(
            model_name="meteorsmainpageconfig",
            name="bolid_path_range",
            field=models.JSONField(
                default=astrophotography.models.default_bolid_path,
                help_text="A list of two integers [min, max] representing the travel distance of a bolid in pixels. Example: [50, 500]",
                verbose_name="Bolid Path Range (px)",
            ),
        ),
        migrations.AlterField(
            model_name="meteorsmainpageconfig",
            name="bolid_streak_range",
            field=models.JSONField(
                default=astrophotography.models.default_bolid_streak,
                help_text="A list of two integers [min, max] representing the visual length (streak) of a bolid. Example: [20, 100]",
                verbose_name="Bolid Streak Range (px)",
            ),
        ),
        migrations.AlterField(
            model_name="meteorsmainpageconfig",
            name="smoke_opacity_range",
            field=models.JSONField(
                default=astrophotography.models.default_smoke_opacity,
                help_text="A list of two floats [min, max] between 0.0 and 1.0 for the smoke trail of a bolid. Example: [0.5, 0.8]",
                verbose_name="Smoke Opacity Range",
            ),
        ),
        migrations.AlterField(
            model_name="meteorsmainpageconfig",
            name="star_duration_range",
            field=models.JSONField(
                default=astrophotography.models.default_star_duration,
                help_text="A list of two floats [min, max] representing the duration (speed) of a regular star. Example: [0.4, 1.2]",
                verbose_name="Star Duration Range (s)",
            ),
        ),
        migrations.AlterField(
            model_name="meteorsmainpageconfig",
            name="star_opacity_range",
            field=models.JSONField(
                default=astrophotography.models.default_star_opacity,
                help_text="A list of two floats [min, max] between 0.0 and 1.0 for regular star brightness. Example: [0.4, 0.8]",
                verbose_name="Star Opacity Range",
            ),
        ),
        migrations.AlterField(
            model_name="meteorsmainpageconfig",
            name="star_path_range",
            field=models.JSONField(
                default=astrophotography.models.default_star_path,
                help_text="A list of two integers [min, max] representing the travel distance of a regular star in pixels. Example: [50, 500]",
                verbose_name="Star Path Range (px)",
            ),
        ),
        migrations.AlterField(
            model_name="meteorsmainpageconfig",
            name="star_streak_range",
            field=models.JSONField(
                default=astrophotography.models.default_star_streak,
                help_text="A list of two integers [min, max] representing the visual length (streak) of a regular star. Example: [100, 200]",
                verbose_name="Star Streak Range (px)",
            ),
        ),
    ]
