# Generated by Django 6.0.1 on 2026-01-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0002_alter_astroimage_celestial_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeteorsMainPageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "random_stars_shooting",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, shooting stars will have randomized flight angles (0-360°). If disabled, they will follow a fixed -45° diagonal path.",
                        verbose_name="Random Shooting Stars",
                    ),
                ),
                (
                    "bolid_chance",
                    models.FloatField(
                        default=0.1,
                        help_text="The probability (0.0 to 1.0) of a regular shooting star being a 'bolid' (fireball). 0.1 means a 10% chance.",
                        verbose_name="Bolid Chance",
                    ),
                ),
                (
                    "bolid_interval",
                    models.FloatField(
                        default=60.0,
                        help_text="The minimum wait time (in seconds) between two bolid spawns to prevent cluster sightings.",
                        verbose_name="Bolid Minimum Interval",
                    ),
                ),
                (
                    "star_path_range",
                    models.JSONField(
                        default=list,
                        help_text="A list of two integers [min, max] representing the travel distance of a regular star in pixels. Example: [50, 500]",
                        verbose_name="Star Path Range (px)",
                    ),
                ),
                (
                    "bolid_path_range",
                    models.JSONField(
                        default=list,
                        help_text="A list of two integers [min, max] representing the travel distance of a bolid in pixels. Example: [50, 500]",
                        verbose_name="Bolid Path Range (px)",
                    ),
                ),
                (
                    "star_streak_range",
                    models.JSONField(
                        default=list,
                        help_text="A list of two integers [min, max] representing the visual length (streak) of a regular star. Example: [100, 200]",
                        verbose_name="Star Streak Range (px)",
                    ),
                ),
                (
                    "star_opacity_range",
                    models.JSONField(
                        default=list,
                        help_text="A list of two floats [min, max] between 0.0 and 1.0 for regular star brightness. Example: [0.4, 0.8]",
                        verbose_name="Star Opacity Range",
                    ),
                ),
                (
                    "bolid_opacity_range",
                    models.JSONField(
                        default=list,
                        help_text="A list of two floats [min, max] between 0.0 and 1.0 for bolid brightness. Example: [0.7, 1.0]",
                        verbose_name="Bolid Opacity Range",
                    ),
                ),
                (
                    "smoke_opacity_range",
                    models.JSONField(
                        default=list,
                        help_text="A list of two floats [min, max] between 0.0 and 1.0 for the smoke trail of a bolid. Example: [0.5, 0.8]",
                        verbose_name="Smoke Opacity Range",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Meteors Main Page Configuration",
                "verbose_name_plural": "Meteors Main Page Configuration",
            },
        ),
    ]
