# Generated by Django 6.0.1 on 2026-02-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0003_fix_tag_slug_schema"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="placetranslation",
            unique_together={("language_code", "master")},
        ),
        migrations.AlterField(
            model_name="placetranslation",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterUniqueTogether(
            name="placetranslation",
            unique_together={("language_code", "master"), ("language_code", "name")},
        ),
    ]
