# Generated by Django 5.2.10 on 2026-01-10 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0003_alter_astroimage_celestial_object"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="astroimage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Astrophotography Image",
                "verbose_name_plural": "Astrophotography Images",
            },
        ),
    ]
