# Generated by Django 6.0.1 on 2026-01-30 20:10

import django_ckeditor_5.fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0003_alter_place_options_alter_astroimage_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astroimage",
            name="exposure_details",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Technical details of the exposure (gain, sub-exposures, total time).",
                verbose_name="Exposure Details",
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="processing_details",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Software and techniques used for post-processing.",
                verbose_name="Processing Details",
            ),
        ),
    ]
