# Generated by Django 6.0.1 on 2026-01-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0003_meteorsmainpageconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meteorsmainpageconfig",
            name="bolid_interval",
            field=models.IntegerField(
                default=60,
                help_text="The minimum wait time (in seconds) between two bolid spawns to prevent cluster sightings. Duration ranges (in seconds) on screen depends on path distance. Speed = PathDistance / Duration. - Smaller duration + Larger distance = High speed. - Larger duration + Smaller distance = Low speed.",
                verbose_name="Bolid Minimum Interval",
            ),
        ),
    ]
