# Generated by Django 6.0.1 on 2026-01-16 19:45

import django_countries.fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0004_uuidtaggeditem_alter_astroimage_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="astroimage",
            name="travel_country",
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
