# Generated by Django 6.0.2 on 2026-02-05 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0004_alter_placetranslation_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={"ordering": ["pk"], "verbose_name": "Place", "verbose_name_plural": "Places"},
        ),
    ]
