# Generated by Django 6.0.1 on 2026-01-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0004_alter_astroimage_exposure_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="astroimage",
            name="zoom",
            field=models.BooleanField(
                default=True,
                help_text="Allow users to zoom this image in detail mode.",
                verbose_name="Zoom",
            ),
        ),
    ]
