# Generated by Django 6.0.1 on 2026-01-16 19:52

import django_countries.fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0005_astroimage_travel_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainPageLocationSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="location_sliders",
                        to="astrophotography.astroimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Main Page Location Slider",
                "verbose_name_plural": "Main Page Location Sliders",
                "ordering": ["country"],
            },
        ),
    ]
