# Generated by Django 6.0.1 on 2026-02-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0005_astroimage_zoom"),
    ]

    operations = [
        migrations.AddField(
            model_name="astroimage",
            name="translations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON providing translations for translatable fields (e.g., {'pl': {'name': '...'}}).",
                verbose_name="Translations",
            ),
        ),
        migrations.AddField(
            model_name="mainpagelocation",
            name="translations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON providing translations for translatable fields (e.g., {'pl': {'highlight_name': '...'}}).",
                verbose_name="Translations",
            ),
        ),
    ]
