# Generated by Django 6.0.2 on 2026-02-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0005_alter_place_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astroimage",
            name="celestial_object",
            field=models.CharField(
                choices=[
                    ("Landscape", "Landscape"),
                    ("Deep Sky", "Deep Sky"),
                    ("Startrails", "Startrails"),
                    ("Solar System", "Solar System"),
                    ("Milky Way", "Milky Way"),
                    ("Northern Lights", "Northern Lights"),
                ],
                default="Landscape",
                max_length=50,
                verbose_name="Celestial Object",
            ),
        ),
    ]
