# Generated by Django 6.0.1 on 2026-01-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0005_meteorsmainpageconfig_bolid_duration_range_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="camera",
            options={
                "ordering": ["name"],
                "verbose_name": "Camera",
                "verbose_name_plural": "Cameras",
            },
        ),
        migrations.AlterModelOptions(
            name="lens",
            options={"ordering": ["name"], "verbose_name": "Lens", "verbose_name_plural": "Lenses"},
        ),
        migrations.AlterModelOptions(
            name="telescope",
            options={
                "ordering": ["name"],
                "verbose_name": "Telescope",
                "verbose_name_plural": "Telescopes",
            },
        ),
        migrations.RemoveField(
            model_name="camera",
            name="model",
        ),
        migrations.RemoveField(
            model_name="lens",
            name="model",
        ),
        migrations.RemoveField(
            model_name="telescope",
            name="model",
        ),
        migrations.AddField(
            model_name="camera",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="lens",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="telescope",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="tripod",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="Name"),
        ),
    ]
