# Generated by Django 6.0.1 on 2026-02-03 00:14

import django.db.models.deletion
import django_ckeditor_5.fields
import django_countries.fields
import parler.fields
import parler.models
from django.db import migrations, models


def migrate_translations(apps, schema_editor):
    # default_lang = settings.LANGUAGE_CODE
    default_lang = "en"  # Hardcoded to strict EN per user requirement for production safety

    # Place
    Place = apps.get_model("astrophotography", "Place")
    PlaceTranslation = apps.get_model("astrophotography", "PlaceTranslation")
    for obj in Place.objects.all():
        if obj.name_old:
            PlaceTranslation.objects.create(
                master_id=obj.pk,
                language_code=default_lang,
                name=obj.name_old
            )

    # AstroImage
    AstroImage = apps.get_model("astrophotography", "AstroImage")
    AstroImageTranslation = apps.get_model("astrophotography", "AstroImageTranslation")
    for obj in AstroImage.objects.all():
        AstroImageTranslation.objects.create(
            master_id=obj.pk,
            language_code=default_lang,
            name=obj.name_old,
            description=obj.description_old,
            exposure_details=obj.exposure_details_old,
            processing_details=obj.processing_details_old
        )
    
    # MainPageLocation
    MainPageLocation = apps.get_model("astrophotography", "MainPageLocation")
    MainPageLocationTranslation = apps.get_model("astrophotography", "MainPageLocationTranslation")
    for obj in MainPageLocation.objects.all():
        MainPageLocationTranslation.objects.create(
            master_id=obj.pk,
            language_code=default_lang,
            highlight_name=obj.highlight_name_old,
            story=obj.story_old
        )

class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0006_astroimage_translations_and_more"),
    ]

    operations = [
        # 1. Rename existing fields to _old (Avoid collision with Parler descriptors)

        migrations.RenameField(
            model_name="place",
            old_name="name",
            new_name="name_old",
        ),

        migrations.RenameField(
            model_name="astroimage",
            old_name="name",
            new_name="name_old",
        ),
        migrations.RenameField(
            model_name="astroimage",
            old_name="translations",
            new_name="translations_old",
        ),
        migrations.RenameField(
            model_name="astroimage",
            old_name="description",
            new_name="description_old",
        ),
        migrations.RenameField(
            model_name="astroimage",
            old_name="exposure_details",
            new_name="exposure_details_old",
        ),
        migrations.RenameField(
            model_name="astroimage",
            old_name="processing_details",
            new_name="processing_details_old",
        ),
        migrations.RenameField(
            model_name="mainpagelocation",
            old_name="highlight_name",
            new_name="highlight_name_old",
        ),
        migrations.RenameField(
            model_name="mainpagelocation",
            old_name="story",
            new_name="story_old",
        ),
        migrations.RenameField(
            model_name="mainpagelocation",
            old_name="translations",
            new_name="translations_old",
        ),

        # 2. Create Translation Models
        migrations.CreateModel(
            name="AstroImageTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A descriptive name for this image.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Optional detailed description of the image.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "exposure_details",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Technical details of the exposure (gain, sub-exposures, total time).",
                        verbose_name="Exposure Details",
                    ),
                ),
                (
                    "processing_details",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Software and techniques used for post-processing.",
                        verbose_name="Processing Details",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="astrophotography.astroimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Astrophotography Image Translation",
                "db_table": "astrophotography_astroimage_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MainPageLocationTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                (
                    "highlight_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom name for the travel highlight (overrides Country/Place).",
                        max_length=100,
                        null=True,
                        verbose_name="Highlight Name",
                    ),
                ),
                (
                    "story",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Optional story or blog text to display above the images.",
                        null=True,
                        verbose_name="Story/Blog Text",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="astrophotography.mainpagelocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Main Page Location Translation",
                "db_table": "astrophotography_mainpagelocation_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PlaceTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        help_text="The name of the specific place or city.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="astrophotography.place",
                    ),
                ),
            ],
            options={
                "verbose_name": "Place Translation",
                "db_table": "astrophotography_place_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),

        # 3. Add Fields (Country) & Alter Options
        migrations.AlterModelOptions(
            name="place",
            options={"verbose_name": "Place", "verbose_name_plural": "Places"},
        ),
        migrations.AddField(
            model_name="place",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="The country where the place is located.",
                max_length=2,
                null=True,
                verbose_name="Country",
            ),
        ),

        # 4. Data Migration
        migrations.RunPython(migrate_translations),

        # 5. Remove Old Fields
        migrations.RemoveField(
            model_name="astroimage",
            name="description_old",
        ),
        migrations.RemoveField(
            model_name="astroimage",
            name="exposure_details_old",
        ),
        migrations.RemoveField(
            model_name="astroimage",
            name="location",
        ),
        migrations.RemoveField(
            model_name="astroimage",
            name="name_old",
        ),
        migrations.RemoveField(
            model_name="astroimage",
            name="processing_details_old",
        ),
        migrations.RemoveField(
            model_name="astroimage",
            name="translations_old",
        ),
        migrations.RemoveField(
            model_name="mainpagebackgroundimage",
            name="description",
        ),
        migrations.RemoveField(
            model_name="mainpagelocation",
            name="country",
        ),
        migrations.RemoveField(
            model_name="mainpagelocation",
            name="highlight_name_old",
        ),
        migrations.RemoveField(
            model_name="mainpagelocation",
            name="story_old",
        ),
        migrations.RemoveField(
            model_name="mainpagelocation",
            name="translations_old",
        ),
        migrations.RemoveField(
            model_name="place",
            name="name_old",
        ),
    ]
