# Generated by Django 6.0.1 on 2026-01-16 20:42

import uuid

import django_countries.fields
import taggit.managers

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0007_mainpagelocationslider_place"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astroimage",
            name="astrobin_url",
            field=models.URLField(
                blank=True,
                help_text="Link to this image on Astrobin (e.g., https://www.astrobin.com/XXXXX/)",
                verbose_name="Astrobin URL",
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="capture_date",
            field=models.DateField(
                help_text="The date when the photo was taken.", verbose_name="Capture Date"
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="celestial_object",
            field=models.CharField(
                choices=[
                    ("Landscape", "Landscape"),
                    ("Deep Sky", "Deep Sky"),
                    ("Startrails", "Startrails"),
                    ("Solar System", "Solar System"),
                    ("Milky Way", "Milky Way"),
                    ("Northern Lights", "Northern Lights"),
                ],
                help_text="The type of celestial object captured.",
                verbose_name="Celestial Object",
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional detailed description of the image.",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="equipment",
            field=models.TextField(
                blank=True,
                help_text="Equipment used (telescope, camera, mount, filters, etc.).",
                verbose_name="Equipment",
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="exposure_details",
            field=models.TextField(
                blank=True,
                help_text="Technical details of the exposure (gain, sub-exposures, total time).",
                verbose_name="Exposure Details",
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="location",
            field=models.CharField(
                help_text="Geographic location where the photo was taken.",
                max_length=255,
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="name",
            field=models.CharField(
                help_text="A descriptive name for this image.", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="path",
            field=models.ImageField(
                help_text="The actual image file to be displayed.",
                upload_to="images/",
                verbose_name="Image File",
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="processing_details",
            field=models.TextField(
                blank=True,
                help_text="Software and techniques used for post-processing.",
                verbose_name="Processing Details",
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="Relevant tags for the image.",
                through="astrophotography.UUIDTaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to="thumbnails/",
                verbose_name="Thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="travel_country",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="The country where the photo was taken (for travel filtering).",
                max_length=2,
                null=True,
                verbose_name="Travel Country",
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="backgroundmainpage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="backgroundmainpage",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional detailed description of the image.",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="backgroundmainpage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="backgroundmainpage",
            name="name",
            field=models.CharField(
                default="Background Image",
                help_text="Identifier for the background image.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="backgroundmainpage",
            name="path",
            field=models.ImageField(
                help_text="The large background image file.",
                upload_to="backgrounds/",
                verbose_name="Image File",
            ),
        ),
        migrations.AlterField(
            model_name="backgroundmainpage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="mainpagelocationslider",
            name="country",
            field=django_countries.fields.CountryField(
                help_text="The country for this travel highlights slider.",
                max_length=2,
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagelocationslider",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="mainpagelocationslider",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select images to display in the slideshow for this location (filtered by country).",
                related_name="location_sliders",
                to="astrophotography.astroimage",
                verbose_name="Images",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagelocationslider",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Toggle visibility on the homepage.",
                verbose_name="Is Active",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagelocationslider",
            name="place",
            field=models.CharField(
                blank=True,
                help_text="Specific city or region (e.g. Hawaii, Tenerife)",
                max_length=100,
                verbose_name="Place/City",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagelocationslider",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
