# Generated by Django 6.0.1 on 2026-02-03 10:57

import django.db.models.deletion
import django_ckeditor_5.fields
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0007_alter_place_options_remove_astroimage_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainpagebackgroundimage",
            name="name",
        ),
        migrations.CreateModel(
            name="MainPageBackgroundImageTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                (
                    "name",
                    models.CharField(
                        default="Background Image",
                        help_text="Identifier for the background image.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Optional detailed description of the image.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="astrophotography.mainpagebackgroundimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Main Page Background Image Translation",
                "db_table": "astrophotography_mainpagebackgroundimage_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
