# Generated by Django 6.0.1 on 2026-01-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0007_alter_camera_name_alter_lens_name_alter_place_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="name",
            field=models.CharField(
                default="",
                help_text="The name or model of the equipment.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="lens",
            name="name",
            field=models.CharField(
                default="",
                help_text="The name or model of the equipment.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(
                default="",
                help_text="The name or model of the equipment.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="telescope",
            name="name",
            field=models.CharField(
                default="",
                help_text="The name or model of the equipment.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="name",
            field=models.CharField(
                default="",
                help_text="The name or model of the equipment.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="tripod",
            name="name",
            field=models.CharField(
                default="",
                help_text="The name or model of the equipment.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
    ]
