# Generated by Django 6.0.2 on 2026-02-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0007_alter_astroimage_celestial_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astroimagetranslation",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="A descriptive name for this image.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagebackgroundimagetranslation",
            name="name",
            field=models.CharField(
                blank=True,
                default="Background Image",
                help_text="Identifier for the background image.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="placetranslation",
            name="name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="tagtranslation",
            name="name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Name"),
        ),
    ]
