# Generated by Django 6.0.1 on 2026-01-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0008_alter_camera_name_alter_lens_name_alter_place_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="camera",
            options={"verbose_name": "Camera", "verbose_name_plural": "Cameras"},
        ),
        migrations.AlterModelOptions(
            name="lens",
            options={"verbose_name": "Lens", "verbose_name_plural": "Lenses"},
        ),
        migrations.AlterModelOptions(
            name="place",
            options={"verbose_name": "Place", "verbose_name_plural": "Places"},
        ),
        migrations.AlterModelOptions(
            name="telescope",
            options={"verbose_name": "Telescope", "verbose_name_plural": "Telescopes"},
        ),
        migrations.AlterModelOptions(
            name="tracker",
            options={"verbose_name": "Tracker", "verbose_name_plural": "Trackers"},
        ),
        migrations.AlterModelOptions(
            name="tripod",
            options={"verbose_name": "Tripod", "verbose_name_plural": "Tripods"},
        ),
    ]
