# Generated by Django 6.0.2 on 2026-02-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0008_alter_astroimagetranslation_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="placetranslation",
            unique_together={("language_code", "master")},
        ),
    ]
