# Generated by Django 6.0.1 on 2026-01-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0008_alter_astroimage_astrobin_url_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BackgroundMainPage",
            new_name="MainPageBackgroundImage",
        ),
        migrations.AlterModelOptions(
            name="mainpagebackgroundimage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Main Page Background Image",
                "verbose_name_plural": "Main Page Background Images",
            },
        ),
    ]
