# Generated by Django 6.0.1 on 2026-01-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0009_alter_camera_options_alter_lens_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="name",
        ),
        migrations.RemoveField(
            model_name="lens",
            name="name",
        ),
        migrations.RemoveField(
            model_name="telescope",
            name="name",
        ),
        migrations.AddField(
            model_name="camera",
            name="model",
            field=models.CharField(
                default="",
                help_text="Camera model and specifications",
                max_length=255,
                verbose_name="Model",
            ),
        ),
        migrations.AddField(
            model_name="lens",
            name="model",
            field=models.CharField(
                default="",
                help_text="Lens model and focal length",
                max_length=255,
                verbose_name="Model",
            ),
        ),
        migrations.AddField(
            model_name="telescope",
            name="model",
            field=models.CharField(
                default="",
                help_text="Telescope model and specifications",
                max_length=255,
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(
                default="",
                help_text="The name of the specific place or city.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="name",
            field=models.CharField(
                default="",
                help_text="Star tracker or mount model",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="tripod",
            name="name",
            field=models.CharField(
                default="", help_text="Tripod model", max_length=255, verbose_name="Name"
            ),
        ),
    ]
