# Generated by Django 6.0.2 on 2026-02-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0009_alter_placetranslation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpagelocationtranslation",
            name="highlight_title",
            field=models.CharField(
                blank=True,
                help_text="Custom title for the highlights page.",
                max_length=255,
                null=True,
                verbose_name="Highlight Title",
            ),
        ),
    ]
