# Generated by Django 6.0.1 on 2026-01-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0009_rename_backgroundmainpage_mainpagebackgroundimage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainpagelocationslider",
            name="place",
        ),
    ]
