# Generated by Django 6.0.1 on 2026-01-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0010_remove_camera_name_remove_lens_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="camera",
            options={
                "ordering": ["model"],
                "verbose_name": "Camera",
                "verbose_name_plural": "Cameras",
            },
        ),
        migrations.AlterModelOptions(
            name="lens",
            options={
                "ordering": ["model"],
                "verbose_name": "Lens",
                "verbose_name_plural": "Lenses",
            },
        ),
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["name"],
                "verbose_name": "Place",
                "verbose_name_plural": "Places",
            },
        ),
        migrations.AlterModelOptions(
            name="telescope",
            options={
                "ordering": ["model"],
                "verbose_name": "Telescope",
                "verbose_name_plural": "Telescopes",
            },
        ),
        migrations.AlterModelOptions(
            name="tracker",
            options={
                "ordering": ["name"],
                "verbose_name": "Tracker",
                "verbose_name_plural": "Trackers",
            },
        ),
        migrations.AlterModelOptions(
            name="tripod",
            options={
                "ordering": ["name"],
                "verbose_name": "Tripod",
                "verbose_name_plural": "Tripods",
            },
        ),
    ]
