# Generated by Django 6.0.1 on 2026-01-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0010_remove_mainpagelocationslider_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpagelocationslider",
            name="place",
            field=models.CharField(
                blank=True,
                help_text="Specific city or region (e.g. Hawaii, Tenerife)",
                max_length=100,
                verbose_name="Place/City",
            ),
        ),
    ]
