# Generated by Django 6.0.2 on 2026-02-21 22:04

import django_countries.fields

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.contrib.postgres.operations import BtreeGistExtension
from django.core.management import call_command
from django.db import migrations, models


def reset_mainpagelocation_sequence(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT setval(
                pg_get_serial_sequence('astrophotography_mainpagelocation', 'id'),
                COALESCE(MAX(id), 1),
                true
            )
            FROM astrophotography_mainpagelocation;
            """
        )


def seed_regions(apps, schema_editor):
    pass
    # call_command("seed_regions")


def reverse_seed_regions(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0010_mainpagelocationtranslation_highlight_title"),
        ("translation", "0001_initial"),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddField(
            model_name="place",
            name="is_region",
            field=models.BooleanField(
                default=False,
                help_text="Mark this place as a broad region (e.g. Hawaii, Scandinavia). Set sub_places to restrict image filtering to specific sub-places. Country is not required for multi-country regions.",
                verbose_name="Is Region",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="sub_places",
            field=models.ManyToManyField(
                blank=True,
                help_text="For regions: explicitly list the sub-places that belong to this region (e.g. Hawaii → Oahu, Big Island; Scandinavia → Norway, Sweden, Finland). Leave empty to fall back to all places in the same country.",
                related_name="parent_regions",
                to="astrophotography.place",
                verbose_name="Sub-Places",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagelocation",
            name="adventure_date",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                help_text="The date range of the expedition. Required for generating the URL slug.",
                verbose_name="Adventure Date Range",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagelocationtranslation",
            name="highlight_title",
            field=models.CharField(
                blank=True,
                help_text="Custom title for the highlights page. Description visible for a given location at the top of the page.",
                max_length=255,
                null=True,
                verbose_name="Highlight Title",
            ),
        ),
        migrations.AlterField(
            model_name="meteorsmainpageconfig",
            name="bolid_interval",
            field=models.IntegerField(
                default=60,
                help_text="Minimum wait time (in seconds) between consecutive bolid sightings to prevent clusters. Note: Bolid speed is calculated as Path Distance / Duration. (Smaller duration + Larger distance = High speed).",
                verbose_name="Bolid Minimum Interval",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="Required for non-region places. Leave blank for multi-country regions (e.g. Scandinavia which spans Norway, Sweden and Finland).",
                max_length=2,
                null=True,
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="tagtranslation",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=100, verbose_name="Slug"),
        ),
        migrations.AddConstraint(
            model_name="mainpagelocation",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[("place", "="), ("adventure_date", "&&")],
                name="exclude_overlapping_adventure_dates",
                violation_error_message="A travel highlight for this Place with an overlapping Date range already exists.",
            ),
        ),
        migrations.RunPython(
            reset_mainpagelocation_sequence, reverse_code=migrations.RunPython.noop
        ),
        # migrations.RunPython(seed_regions, reverse_code=reverse_seed_regions),
    ]
