# Generated by Django 6.0.1 on 2026-01-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0011_alter_camera_options_alter_lens_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="camera",
            options={"verbose_name": "Camera", "verbose_name_plural": "Cameras"},
        ),
        migrations.AlterModelOptions(
            name="lens",
            options={"verbose_name": "Lens", "verbose_name_plural": "Lenses"},
        ),
        migrations.AlterModelOptions(
            name="telescope",
            options={"verbose_name": "Telescope", "verbose_name_plural": "Telescopes"},
        ),
        migrations.AlterModelOptions(
            name="tracker",
            options={"verbose_name": "Tracker", "verbose_name_plural": "Trackers"},
        ),
        migrations.AlterModelOptions(
            name="tripod",
            options={"verbose_name": "Tripod", "verbose_name_plural": "Tripods"},
        ),
        migrations.RemoveField(
            model_name="tracker",
            name="name",
        ),
        migrations.RemoveField(
            model_name="tripod",
            name="name",
        ),
        migrations.AddField(
            model_name="tracker",
            name="model",
            field=models.CharField(
                default="",
                help_text="The model identifiers or name of the equipment.",
                max_length=255,
                verbose_name="Model",
            ),
        ),
        migrations.AddField(
            model_name="tripod",
            name="model",
            field=models.CharField(
                default="",
                help_text="The model identifiers or name of the equipment.",
                max_length=255,
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="model",
            field=models.CharField(
                default="",
                help_text="The model identifiers or name of the equipment.",
                max_length=255,
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="lens",
            name="model",
            field=models.CharField(
                default="",
                help_text="The model identifiers or name of the equipment.",
                max_length=255,
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="telescope",
            name="model",
            field=models.CharField(
                default="",
                help_text="The model identifiers or name of the equipment.",
                max_length=255,
                verbose_name="Model",
            ),
        ),
    ]
