# Generated by Django 6.0.1 on 2026-01-16 20:53

import django_countries.fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0011_mainpagelocationslider_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="astroimage",
            name="location",
        ),
        migrations.RemoveField(
            model_name="astroimage",
            name="travel_country",
        ),
        migrations.AddField(
            model_name="astroimage",
            name="location_new",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="The country where the photo was taken.",
                max_length=2,
                null=True,
                verbose_name="Country",
            ),
        ),
        migrations.AddField(
            model_name="astroimage",
            name="place",
            field=models.CharField(
                blank=True,
                help_text="Specific city or region (e.g. Hawaii, Tenerife).",
                max_length=255,
                verbose_name="Place/City",
            ),
        ),
    ]
