# Generated by Django 6.0.2 on 2026-02-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0011_fix_mainpagelocation_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="is_region",
            field=models.BooleanField(
                default=False,
                help_text="Mark this place as a broad region (e.g. Canary Islands, Hawaii). When set, image filtering on MainPageLocation will include all images from places in the same country rather than this exact place.",
                verbose_name="Is Region",
            ),
        ),
        migrations.AlterField(
            model_name="meteorsmainpageconfig",
            name="bolid_interval",
            field=models.IntegerField(
                default=60,
                help_text="Minimum wait time (in seconds) between consecutive bolid sightings to prevent clusters. Note: Bolid speed is calculated as Path Distance / Duration. (Smaller duration + Larger distance = High speed).",
                verbose_name="Bolid Minimum Interval",
            ),
        ),
    ]
