# Generated by Django 6.0.2 on 2026-03-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0011_place_is_region_place_sub_places_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="astroimage",
            name="legacy_path",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Original file path before WebP conversion. Used for rollback via the Admin serve_webp_images toggle.",
                null=True,
                upload_to="images/",
                verbose_name="Legacy Image Path",
            ),
        ),
        migrations.AddField(
            model_name="mainpagebackgroundimage",
            name="legacy_path",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Original file path before WebP conversion. Used for rollback via the Admin serve_webp_images toggle.",
                null=True,
                upload_to="images/",
                verbose_name="Legacy Image Path",
            ),
        ),
    ]
