# Generated by Django 6.0.1 on 2026-01-27 10:16

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    AstroImage = apps.get_model("astrophotography", "AstroImage")
    for image in AstroImage.objects.all():
        if not image.slug:
            base_slug = slugify(image.name)
            slug = base_slug
            n = 1
            while AstroImage.objects.filter(slug=slug).exclude(pk=image.pk).exists():
                slug = f"{base_slug}-{n}"
                n += 1
            image.slug = slug
            image.save()


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0012_alter_camera_options_alter_lens_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="astroimage",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="SEO friendly URL slug.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="astroimage",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="SEO friendly URL slug.",
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
