# Generated by Django 6.0.2 on 2026-02-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0012_add_place_is_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagtranslation",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=100, verbose_name="Slug"),
        ),
    ]
