# Generated by Django 6.0.1 on 2026-01-16 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0012_remove_astroimage_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="astroimage",
            old_name="location_new",
            new_name="location",
        ),
    ]
