# Generated by Django 6.0.1 on 2026-01-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0012_alter_camera_options_alter_lens_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="astroimage",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="SEO friendly URL slug.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
