# Generated by Django 6.0.2 on 2026-02-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0013_alter_tagtranslation_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpagelocationtranslation",
            name="highlight_title",
            field=models.CharField(
                blank=True,
                help_text="Custom title for the highlights page. Description visible for a given location at the top of the page.",
                max_length=255,
                null=True,
                verbose_name="Highlight Title",
            ),
        ),
    ]
