# Generated by Django 6.0.1 on 2026-01-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0013_rename_location_new_astroimage_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the specific place or city.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Place",
                "verbose_name_plural": "Places",
                "ordering": ["name"],
            },
        ),
        migrations.RenameField(
            model_name="astroimage",
            old_name="place",
            new_name="place_old",
        ),
        migrations.RenameField(
            model_name="mainpagelocationslider",
            old_name="place",
            new_name="place_old",
        ),
    ]
