# Generated by Django 6.0.1 on 2026-01-16 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0014_place_rename_place_astroimage_place_old_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="astroimage",
            name="place",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific city or region (e.g. Hawaii, Tenerife).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="astrophotography.place",
                verbose_name="Place/City",
            ),
        ),
        migrations.AddField(
            model_name="mainpagelocationslider",
            name="place",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific city or region (e.g. Hawaii, Tenerife)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="astrophotography.place",
                verbose_name="Place/City",
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="place_old",
            field=models.CharField(
                blank=True,
                help_text="Old text place field.",
                max_length=255,
                verbose_name="Place/City",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagelocationslider",
            name="place_old",
            field=models.CharField(
                blank=True,
                help_text="Old text place field.",
                max_length=100,
                verbose_name="Place/City",
            ),
        ),
    ]
