# Generated by Django 6.0.2 on 2026-02-20 21:47

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0014_alter_mainpagelocationtranslation_highlight_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpagelocation",
            name="adventure_date",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                default="['2025-01-01', '2025-01-31']",
                help_text="The date range of the expedition. Required for generating the URL slug.",
                verbose_name="Adventure Date Range",
            ),
            preserve_default=False,
        ),
    ]
