# Generated by Django 6.0.1 on 2026-01-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0014_populate_astroimage_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astroimage",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="SEO friendly URL slug.",
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
