# Generated by Django 6.0.3 on 2026-04-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0015_alter_astroimage_original_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="astroimage",
            name="calculated_exposure_hours",
            field=models.FloatField(
                default=0,
                help_text="Internal LLM-derived exposure duration stored in hours.",
                verbose_name="Calculated Exposure Hours",
            ),
        ),
    ]
