# Generated by Django 6.0.1 on 2026-01-16 21:53

from django.db import migrations


def migrate_place_data(apps, schema_editor):
    Place = apps.get_model("astrophotography", "Place")
    AstroImage = apps.get_model("astrophotography", "AstroImage")
    MainPageLocationSlider = apps.get_model("astrophotography", "MainPageLocationSlider")

    # Migrate AstroImage
    for obj in AstroImage.objects.all():
        if obj.place_old:
            place_obj, _ = Place.objects.get_or_create(name=obj.place_old)
            obj.place = place_obj
            obj.save()

    # Migrate MainPageLocationSlider
    for obj in MainPageLocationSlider.objects.all():
        if obj.place_old:
            place_obj, _ = Place.objects.get_or_create(name=obj.place_old)
            obj.place = place_obj
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0015_astroimage_place_mainpagelocationslider_place_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_place_data),
    ]
