# astrophotography/migrations/0016_place_region_relations.py
# Generated by Django 6.0.2 on 2026-02-21 15:00

import django_countries.fields

from django.core.management import call_command
from django.db import migrations, models


def seed_regions(apps, schema_editor):
    call_command("seed_regions")


def reverse_seed_regions(apps, schema_editor):
    pass  # Seeded data is left in place on rollback to avoid data loss


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0015_alter_mainpagelocation_adventure_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="sub_places",
            field=models.ManyToManyField(
                blank=True,
                help_text="For regions: explicitly list the sub-places that belong to this region (e.g. Hawaii → Oahu, Big Island; Scandinavia → Norway, Sweden, Finland). Leave empty to fall back to all places in the same country.",
                related_name="parent_regions",
                to="astrophotography.place",
                verbose_name="Sub-Places",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="Required for non-region places. Leave blank for multi-country regions (e.g. Scandinavia which spans Norway, Sweden and Finland).",
                max_length=2,
                null=True,
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="is_region",
            field=models.BooleanField(
                default=False,
                help_text="Mark this place as a broad region (e.g. Hawaii, Scandinavia). Set sub_places to restrict image filtering to specific sub-places. Country is not required for multi-country regions.",
                verbose_name="Is Region",
            ),
        ),
        migrations.RunPython(seed_regions, reverse_code=reverse_seed_regions),
    ]
