# Generated by Django 6.0.1 on 2026-01-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0016_migrate_place_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="astroimage",
            name="place_old",
        ),
        migrations.RemoveField(
            model_name="mainpagelocationslider",
            name="place_old",
        ),
    ]
