# Generated by Django 6.0.2 on 2026-02-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0016_place_region_relations"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mainpagelocation",
            constraint=models.UniqueConstraint(
                fields=("place", "adventure_date"),
                name="unique_place_adventure_date",
                violation_error_message="A travel highlight for this Place and Date already exists.",
            ),
        ),
    ]
