# Generated by Django 6.0.1 on 2026-01-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0017_remove_astroimage_place_old_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpagelocationslider",
            name="highlight_name",
            field=models.CharField(
                blank=True,
                help_text="Optional custom name for the travel highlight (overrides Country/Place).",
                max_length=100,
                null=True,
                verbose_name="Highlight Name",
            ),
        ),
    ]
