# Generated by Django 6.0.3 on 2026-04-20 15:21

from django.db import migrations, models

import common.utils.image


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0017_baseimage_original_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astroimage",
            name="original",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Uploaded source image for the next BaseImage contract.",
                null=True,
                upload_to=common.utils.image.SeededImageUploadTo("base_upload_dir", "original"),
                verbose_name="Original Image Source",
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="original_image",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Legacy original-image field kept during the BaseImage refactor. Used for rollback via the Admin serve_webp_images toggle. TODO: legacy, will be removed in future.",
                null=True,
                upload_to=common.utils.image.SeededImageUploadTo("base_upload_dir", "original"),
                verbose_name="Original Image",
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="original_webp",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Derived WebP image for the next BaseImage contract.",
                null=True,
                upload_to=common.utils.image.SeededImageUploadTo("base_upload_dir", "webp"),
                verbose_name="Original Image WebP",
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="path",
            field=models.ImageField(
                help_text="Legacy image field kept during the BaseImage refactor. TODO: legacy, will be removed in future.",
                upload_to="images/",
                verbose_name="Image File",
            ),
        ),
        migrations.AlterField(
            model_name="astroimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to=common.utils.image.SeededImageUploadTo("base_upload_dir", "thumbnail"),
                verbose_name="Thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagebackgroundimage",
            name="original",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Uploaded source image for the next BaseImage contract.",
                null=True,
                upload_to=common.utils.image.SeededImageUploadTo("base_upload_dir", "original"),
                verbose_name="Original Image Source",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagebackgroundimage",
            name="original_image",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Legacy original-image field kept during the BaseImage refactor. Used for rollback via the Admin serve_webp_images toggle. TODO: legacy, will be removed in future.",
                null=True,
                upload_to=common.utils.image.SeededImageUploadTo("base_upload_dir", "original"),
                verbose_name="Original Image",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagebackgroundimage",
            name="original_webp",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Derived WebP image for the next BaseImage contract.",
                null=True,
                upload_to=common.utils.image.SeededImageUploadTo("base_upload_dir", "webp"),
                verbose_name="Original Image WebP",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagebackgroundimage",
            name="path",
            field=models.ImageField(
                help_text="Legacy background image field kept during the BaseImage refactor. TODO: legacy, will be removed in future.",
                upload_to="backgrounds/",
                verbose_name="Image File",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagebackgroundimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to=common.utils.image.SeededImageUploadTo("base_upload_dir", "thumbnail"),
                verbose_name="Thumbnail",
            ),
        ),
    ]
