# Generated by Django 6.0.2 on 2026-02-21 18:35

import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0017_mainpagelocation_unique_place_adventure_date"),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.RemoveConstraint(
            model_name="mainpagelocation",
            name="unique_place_adventure_date",
        ),
        migrations.AddConstraint(
            model_name="mainpagelocation",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[("place", "="), ("adventure_date", "&&")],
                name="exclude_overlapping_adventure_dates",
                violation_error_message="A travel highlight for this Place with an overlapping Date range already exists.",
            ),
        ),
    ]
