# Generated by Django 6.0.1 on 2026-01-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0018_mainpagelocationslider_highlight_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpagelocationslider",
            name="country_slug",
            field=models.SlugField(
                blank=True,
                help_text="Auto-generated slug for the country.",
                max_length=100,
                verbose_name="Country Slug",
            ),
        ),
        migrations.AddField(
            model_name="mainpagelocationslider",
            name="place_slug",
            field=models.SlugField(
                blank=True,
                help_text="Auto-generated slug for the place.",
                max_length=100,
                null=True,
                verbose_name="Place Slug",
            ),
        ),
    ]
