# Generated by Django 6.0.3 on 2026-06-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0019_remove_astroimage_original_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="astroimage",
            name="original_webp",
        ),
        migrations.RemoveField(
            model_name="mainpagebackgroundimage",
            name="original_webp",
        ),
    ]
