# Generated by Django 6.0.1 on 2026-01-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0019_mainpagelocationslider_country_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpagelocationslider",
            name="story",
            field=models.TextField(
                blank=True,
                help_text="Optional story or blog text to display above the images.",
                null=True,
                verbose_name="Story/Blog Text",
            ),
        ),
    ]
