# Generated by Django 6.0.1 on 2026-01-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0020_mainpagelocationslider_story"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MainPageLocationSlider",
            new_name="MainPageLocation",
        ),
        migrations.AlterModelOptions(
            name="mainpagelocation",
            options={
                "ordering": ["country"],
                "verbose_name": "Main Page Location",
                "verbose_name_plural": "Main Page Locations",
            },
        ),
    ]
