# Generated by Django 6.0.1 on 2026-01-21 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0022_add_background_image_to_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpagelocation",
            name="background_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional specific background image for this location's page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="location_backgrounds",
                to="astrophotography.astroimage",
                verbose_name="Custom Background",
            ),
        ),
    ]
