# Generated by Django 6.0.1 on 2026-01-21 13:30

import django_ckeditor_5.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0023_change_background_image_to_astroimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpagelocation",
            name="background_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional specific background image for this location's page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="location_backgrounds",
                to="astrophotography.astroimage",
                verbose_name="Background Image",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagelocation",
            name="story",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Optional story or blog text to display above the images.",
                null=True,
                verbose_name="Story/Blog Text",
            ),
        ),
    ]
