# Generated by Django 6.0.1 on 2026-01-21 13:33

import django_ckeditor_5.fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0024_alter_mainpagelocation_background_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astroimage",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Optional detailed description of the image.",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="mainpagebackgroundimage",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Optional detailed description of the image.",
                verbose_name="Description",
            ),
        ),
    ]
