# Generated by Django 6.0.1 on 2026-01-21 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0025_alter_astroimage_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "telescope",
                    models.CharField(
                        blank=True,
                        help_text="Telescope model and specifications",
                        max_length=255,
                        verbose_name="Telescope",
                    ),
                ),
                (
                    "camera",
                    models.CharField(
                        blank=True,
                        help_text="Camera model and specifications",
                        max_length=255,
                        verbose_name="Camera",
                    ),
                ),
                (
                    "tracker",
                    models.CharField(
                        blank=True,
                        help_text="Star tracker or mount model",
                        max_length=255,
                        verbose_name="Tracker/Mount",
                    ),
                ),
                (
                    "tripod",
                    models.CharField(
                        blank=True, help_text="Tripod model", max_length=255, verbose_name="Tripod"
                    ),
                ),
                (
                    "lens",
                    models.CharField(
                        blank=True,
                        help_text="Lens model and focal length",
                        max_length=255,
                        verbose_name="Lens",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment",
                "verbose_name_plural": "Equipment",
                "ordering": ["camera", "telescope"],
            },
        ),
        # Remove old equipment TextField
        migrations.RemoveField(
            model_name="astroimage",
            name="equipment",
        ),
        # Add new equipment ForeignKey
        migrations.AddField(
            model_name="astroimage",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                help_text="Equipment setup used for this image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="astrophotography.equipment",
                verbose_name="Equipment",
            ),
        ),
    ]
