# Generated by Django 6.0.1 on 2026-01-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0026_equipment_alter_astroimage_equipment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="astroimage",
            name="equipment",
        ),
        migrations.AddField(
            model_name="astroimage",
            name="equipment",
            field=models.ManyToManyField(
                blank=True,
                help_text="Equipment used for this image.",
                to="astrophotography.equipment",
                verbose_name="Equipment",
            ),
        ),
    ]
