# Generated by Django 6.0.1 on 2026-01-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0027_remove_astroimage_equipment_astroimage_equipment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="astroimage",
            name="equipment",
        ),
        migrations.AddField(
            model_name="astroimage",
            name="camera",
            field=models.CharField(
                blank=True,
                help_text="Camera model and specifications",
                max_length=255,
                verbose_name="Camera",
            ),
        ),
        migrations.AddField(
            model_name="astroimage",
            name="lens",
            field=models.CharField(
                blank=True,
                help_text="Lens model and focal length",
                max_length=255,
                verbose_name="Lens",
            ),
        ),
        migrations.AddField(
            model_name="astroimage",
            name="telescope",
            field=models.CharField(
                blank=True,
                help_text="Telescope model and specifications",
                max_length=255,
                verbose_name="Telescope",
            ),
        ),
        migrations.AddField(
            model_name="astroimage",
            name="tracker",
            field=models.CharField(
                blank=True,
                help_text="Star tracker or mount model",
                max_length=255,
                verbose_name="Tracker/Mount",
            ),
        ),
        migrations.AddField(
            model_name="astroimage",
            name="tripod",
            field=models.CharField(
                blank=True, help_text="Tripod model", max_length=255, verbose_name="Tripod"
            ),
        ),
        migrations.DeleteModel(
            name="Equipment",
        ),
    ]
