# Generated by Django 6.0.1 on 2026-01-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0028_remove_astroimage_equipment_astroimage_camera_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Camera model and specifications",
                        max_length=255,
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Camera",
                "verbose_name_plural": "Cameras",
                "ordering": ["model"],
            },
        ),
        migrations.CreateModel(
            name="Lens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Lens model and focal length",
                        max_length=255,
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lens",
                "verbose_name_plural": "Lenses",
                "ordering": ["model"],
            },
        ),
        migrations.RemoveField(
            model_name="astroimage",
            name="camera",
        ),
        migrations.RemoveField(
            model_name="astroimage",
            name="lens",
        ),
        migrations.AddField(
            model_name="astroimage",
            name="camera",
            field=models.ManyToManyField(
                blank=True,
                help_text="Camera model and specifications",
                to="astrophotography.camera",
                verbose_name="Camera",
            ),
        ),
        migrations.AddField(
            model_name="astroimage",
            name="lens",
            field=models.ManyToManyField(
                blank=True,
                help_text="Lens model and focal length",
                to="astrophotography.lens",
                verbose_name="Lens",
            ),
        ),
    ]
