# Generated by Django 6.0.1 on 2026-01-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0029_camera_lens_remove_astroimage_camera_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Telescope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Telescope model and specifications",
                        max_length=255,
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telescope",
                "verbose_name_plural": "Telescopes",
                "ordering": ["model"],
            },
        ),
        migrations.CreateModel(
            name="Tracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Star tracker or mount model", max_length=255, verbose_name="Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracker",
                "verbose_name_plural": "Trackers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tripod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Tripod model", max_length=255, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Tripod",
                "verbose_name_plural": "Tripods",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="astroimage",
            name="telescope",
        ),
        migrations.RemoveField(
            model_name="astroimage",
            name="tracker",
        ),
        migrations.RemoveField(
            model_name="astroimage",
            name="tripod",
        ),
        migrations.AddField(
            model_name="astroimage",
            name="telescope",
            field=models.ManyToManyField(
                blank=True,
                help_text="Telescope model and specifications",
                to="astrophotography.telescope",
                verbose_name="Telescope",
            ),
        ),
        migrations.AddField(
            model_name="astroimage",
            name="tracker",
            field=models.ManyToManyField(
                blank=True,
                help_text="Star tracker or mount model",
                to="astrophotography.tracker",
                verbose_name="Tracker/Mount",
            ),
        ),
        migrations.AddField(
            model_name="astroimage",
            name="tripod",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tripod model",
                to="astrophotography.tripod",
                verbose_name="Tripod",
            ),
        ),
    ]
