# Generated by Django 6.0.1 on 2026-01-21 21:55

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0030_telescope_tracker_tripod_remove_astroimage_telescope_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpagelocation",
            name="adventure_date",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                blank=True,
                help_text="The date range of the expedition.",
                null=True,
                verbose_name="Adventure Date Range",
            ),
        ),
    ]
