# Generated by Django 6.0.1 on 2026-01-21 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0031_mainpagelocation_adventure_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mainpagelocation",
            options={
                "ordering": ["-adventure_date"],
                "verbose_name": "Main Page Location",
                "verbose_name_plural": "Main Page Locations",
            },
        ),
    ]
