# Generated by Django 6.0.1 on 2026-01-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0032_alter_mainpagelocation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpagebackgroundimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to="thumbnails/",
                verbose_name="Thumbnail",
            ),
        ),
    ]
