# Generated by Django 4.2.25 on 2026-01-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFormSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable or disable the contact form endpoint. When disabled, all submissions will be rejected.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact Form Settings",
                "verbose_name_plural": "Contact Form Settings",
            },
        ),
    ]
