# Generated by Django 5.2.3 on 2026-01-10 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=10000)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "about_me_image",
                    models.ImageField(blank=True, null=True, upload_to="about_me_images/"),
                ),
                (
                    "about_me_image2",
                    models.ImageField(blank=True, null=True, upload_to="about_me_images/"),
                ),
                ("website", models.URLField(blank=True, max_length=200)),
                ("github_profile", models.URLField(blank=True, max_length=200)),
                ("linkedin_profile", models.URLField(blank=True, max_length=200)),
                (
                    "astrobin_url",
                    models.URLField(
                        blank=True,
                        help_text="Your Astrobin profile URL (e.g., https://www.astrobin.com/users/yourusername/)",
                        max_length=200,
                    ),
                ),
                (
                    "fb_url",
                    models.URLField(
                        blank=True,
                        help_text="Your Facebook profile or page URL",
                        max_length=200,
                    ),
                ),
                (
                    "ig_url",
                    models.URLField(
                        blank=True,
                        help_text="Your Instagram profile URL (e.g., https://www.instagram.com/yourusername/)",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
            managers=[
                ("objects", "users.models.UserManager"),
            ],
        ),
        migrations.CreateModel(
            name="UserLoginAttempts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Datetime when the login attempt occurred",
                    ),
                ),
                (
                    "counter",
                    models.IntegerField(
                        default=1, help_text="Number of login attempts (counter)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Login Attempt",
                "verbose_name_plural": "User Login Attempts",
                "ordering": ["-attempted_at"],
            },
        ),
    ]
