# Generated by Django 6.0.1 on 2026-01-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Short description/hero text (approx. 200 words)",
                max_length=1500,
            ),
        ),
    ]
