# Generated by Django 6.0.1 on 2026-02-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="translations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON providing translations for translatable fields (e.g., {'pl': {'title': '...'}}).",
                verbose_name="Translations",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="translations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON providing translations for translatable fields (e.g., {'pl': {'short_description': '...'}}).",
                verbose_name="Translations",
            ),
        ),
    ]
