# Generated by Django 6.0.1 on 2026-02-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_translations_user_translations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="translations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON translations (e.g., {'pl': {'title': '...'}}).",
                verbose_name="Translations",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="translations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON translations (e.g., {'pl': {'short_description': '...'}}).",
                verbose_name="Translations",
            ),
        ),
    ]
