# Generated by Django 4.2.25 on 2026-01-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userloginattempts",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userloginattempts",
            name="updated_at",
        ),
    ]
