# Generated by Django 5.2.10 on 2026-01-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
        ("users", "0003_remove_login_attempts_timestamps"),
    ]

    operations = []
