# Generated by Django 6.0.1 on 2026-01-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="short_description",
            field=models.TextField(
                blank=True,
                help_text="Hero section text. Split by the first period ('.'): the first segment will be large/bold, following text will be smaller.",
            ),
        ),
    ]
