# Generated by Django 6.0.2 on 2026-02-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_translations_alter_user_translations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="bio",
            new_name="bio_old",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="short_description",
            new_name="short_description_old",
        ),
    ]
