# Generated by Django 6.0.2 on 2026-02-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_bio_user_bio_old_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="translations",
            new_name="translations_json_old",
        ),
        migrations.AlterField(
            model_name="user",
            name="translations_json_old",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON translations (e.g., {'pl': {'short_description': '...'}}).",
                verbose_name="Translations (JSON - Legacy)",
            ),
        ),
    ]
