# Generated by Django 6.0.1 on 2026-01-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contact_email",
            field=models.EmailField(
                blank=True, help_text="Public contact email displayed in footer", max_length=254
            ),
        ),
    ]
