# Generated by Django 5.2.10 on 2026-01-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_merge_20260110_2049"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
