# Generated by Django 6.0.2 on 2026-02-05 22:27

import django_ckeditor_5.fields
import parler.fields
import parler.models

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_translations_user_translations_json_old"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User Account", "verbose_name_plural": "Users"},
        ),
        migrations.CreateModel(
            name="UserTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        help_text="Hero section text. Split by the first period ('.'): the first segment will be large/bold, following text will be smaller.",
                    ),
                ),
                ("bio", django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name="Bio")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Account Translation",
                "db_table": "users_user_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
