# Generated by Django 6.0.1 on 2026-01-11 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="astrobin_url",
            field=models.URLField(blank=True, help_text="Your Astrobin profile URL"),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, help_text="General/Global bio about you", max_length=10000
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="ig_url",
            field=models.URLField(blank=True, help_text="Your Instagram profile URL"),
        ),
        migrations.CreateModel(
            name="PersonaProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PROGRAMMING", "Programming"), ("ASTRO", "Astrophotography")],
                        help_text="The niche this profile represents",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Public title, e.g. 'Software Engineer'", max_length=255
                    ),
                ),
                ("specific_bio", models.TextField(help_text="Persona-specific bio/description")),
                ("github_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                (
                    "astrobin_url",
                    models.URLField(blank=True, help_text="Link to your Astrobin profile"),
                ),
                ("fb_url", models.URLField(blank=True)),
                ("ig_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona Profile",
                "verbose_name_plural": "Persona Profiles",
                "ordering": ["type"],
            },
        ),
    ]
