# Generated by Django 6.0.1 on 2026-01-21 09:32

import django_ckeditor_5.fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name="Bio"),
        ),
    ]
