# Generated by Django 6.0.2 on 2026-02-05 22:30

from django.conf import settings
from django.db import migrations


def migrate_data(apps, schema_editor):
    User = apps.get_model("users", "User")
    UserTranslation = apps.get_model("users", "UserTranslation")

    for user in User.objects.all():
        if user.short_description_old or user.bio_old:
            UserTranslation.objects.create(
                master=user,
                language_code=settings.LANGUAGE_CODE,  # Use default language (usually 'en')
                short_description=user.short_description_old,
                bio=user.bio_old,
            )


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_options_usertranslation"),
    ]

    operations = [
        migrations.RunPython(migrate_data, reverse_migration),
    ]
