# Generated by Django 6.0.1 on 2026-01-11 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_move_persona_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="astrobin_url",
        ),
        migrations.RemoveField(
            model_name="user",
            name="fb_url",
        ),
        migrations.RemoveField(
            model_name="user",
            name="github_profile",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ig_url",
        ),
        migrations.RemoveField(
            model_name="user",
            name="linkedin_profile",
        ),
    ]
