# Generated by Django 6.0.2 on 2026-02-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_migrate_user_translations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelOptions(
            name="usertranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "User Translation",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio_old",
        ),
        migrations.RemoveField(
            model_name="user",
            name="short_description_old",
        ),
        migrations.RemoveField(
            model_name="user",
            name="translations_json_old",
        ),
    ]
