# Generated by Django 6.0.1 on 2026-01-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_user_astrobin_url_remove_user_fb_url_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PersonaProfile",
            new_name="Profile",
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ["type"],
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="website",
        ),
    ]
