# Generated by Django 6.0.2 on 2026-02-06 08:34

import parler.fields
import parler.models

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_options_alter_usertranslation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
        migrations.AlterUniqueTogether(
            name="profile",
            unique_together={("user", "type")},
        ),
        migrations.AlterField(
            model_name="profile",
            name="astrobin_url",
            field=models.URLField(blank=True, verbose_name="AstroBin URL"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="fb_url",
            field=models.URLField(blank=True, verbose_name="Facebook URL"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="github_url",
            field=models.URLField(blank=True, verbose_name="GitHub URL"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="ig_url",
            field=models.URLField(blank=True, verbose_name="Instagram URL"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin_url",
            field=models.URLField(blank=True, verbose_name="LinkedIn URL"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="type",
            field=models.CharField(
                choices=[
                    ("PROGRAMMING", "Programming Profile"),
                    ("ASTRO", "Astrophotography Profile"),
                ],
                default="PROGRAMMING",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="specific_bio",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="title",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="translations",
        ),
        migrations.CreateModel(
            name="ProfileTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("specific_bio", models.TextField(blank=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Translation",
                "db_table": "users_profile_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
