# Generated by Django 6.0.1 on 2026-01-11 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_rename_personaprofile_profile_alter_profile_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserLoginAttempts",
        ),
    ]
