# Generated by Django 6.0.2 on 2026-03-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_profile_options_alter_profile_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about_me_image2_legacy",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Original about_me_image2 before WebP conversion. Used for rollback.",
                null=True,
                upload_to="about_me_images/",
                verbose_name="Legacy About Me Image 2",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="about_me_image_legacy",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Original about_me_image before WebP conversion. Used for rollback.",
                null=True,
                upload_to="about_me_images/",
                verbose_name="Legacy About Me Image",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_legacy",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Original avatar before WebP conversion. Used for rollback.",
                null=True,
                upload_to="avatars/",
                verbose_name="Legacy Avatar",
            ),
        ),
    ]
