# Generated by Django 6.0.2 on 2026-03-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_about_me_image2_legacy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about_me_image2_legacy",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Original about_me_image2 before WebP conversion. Used for rollback. TODO: Will be removed in future versions.",
                null=True,
                upload_to="about_me_images/",
                verbose_name="Legacy About Me Image 2",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="about_me_image_legacy",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Original about_me_image before WebP conversion. Used for rollback. TODO: Will be removed in future versions.",
                null=True,
                upload_to="about_me_images/",
                verbose_name="Legacy About Me Image",
            ),
        ),
    ]
