# Generated by Django 6.0.2 on 2026-03-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_rename_legacy_fields_original_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about_me_image2_original_image",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Original about_me_image2 before WebP conversion. Used for rollback. ",
                null=True,
                upload_to="about_me_images/",
                verbose_name="Original About Me Image 2",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="about_me_image_original_image",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Original about_me_image before WebP conversion. Used for rollback. ",
                null=True,
                upload_to="about_me_images/",
                verbose_name="Original About Me Image",
            ),
        ),
    ]
