# Generated by Django 6.0.3 on 2026-06-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_user_cropped_image_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="about_me_image2_webp",
        ),
        migrations.RemoveField(
            model_name="user",
            name="about_me_image_webp",
        ),
        migrations.RemoveField(
            model_name="user",
            name="avatar_webp",
        ),
    ]
