# Generated by Django 6.0.1 on 2026-01-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LandingPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "contact_form_enabled",
                    models.BooleanField(default=True, verbose_name="Contact Form Enabled"),
                ),
                (
                    "travel_highlights_enabled",
                    models.BooleanField(default=True, verbose_name="Travel Highlights Enabled"),
                ),
                (
                    "programming_enabled",
                    models.BooleanField(default=True, verbose_name="Programming Section Enabled"),
                ),
                (
                    "lastimages_enabled",
                    models.BooleanField(default=True, verbose_name="Last Images Section Enabled"),
                ),
                (
                    "meteors_enabled",
                    models.BooleanField(default=True, verbose_name="Meteors Enabled"),
                ),
            ],
            options={
                "verbose_name": "Landing Page Settings",
                "verbose_name_plural": "Landing Page Settings",
            },
        ),
    ]
