# Generated by Django 6.0.1 on 2026-01-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpagesettings",
            name="lastimages_enabled",
            field=models.BooleanField(default=True, verbose_name="Last Images Section Enabled"),
        ),
    ]
