# Generated by Django 6.0.2 on 2026-03-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpagesettings",
            name="serve_webp_images",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, serves WebP-converted images. Disable to fall back to the original legacy images for rollback.",
                verbose_name="Serve WebP Images",
            ),
        ),
    ]
