# Generated by Django 6.0.1 on 2026-01-25 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0005_meteorsmainpageconfig_bolid_duration_range_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="meteors_enabled",
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="meteors",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the configuration to enable meteors. Leave empty to disable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="astrophotography.meteorsmainpageconfig",
                verbose_name="Meteors Configuration",
            ),
        ),
    ]
