# Generated by Django 6.0.1 on 2026-02-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_translationtask"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="translationtask",
            name="core_transl_content_8748c9_idx",
        ),
        migrations.RemoveIndex(
            model_name="translationtask",
            name="core_transl_status_8857fc_idx",
        ),
        migrations.DeleteModel(
            name="TranslationTask",
        ),
    ]
