# Generated by Django 6.0.1 on 2026-01-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_landingpagesettings_lastimages_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="location_slider_enabled",
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="travel_highlights_enabled",
            field=models.BooleanField(default=True, verbose_name="Travel Highlights Enabled"),
        ),
    ]
