# Generated by Django 6.0.2 on 2026-03-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_landingpagesettings_serve_webp_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpagesettings",
            name="serve_webp_images",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, serves WebP-converted images. Disable to fall back to the original legacy images for rollback. Will be removed in future.",
                verbose_name="Serve WebP Images",
            ),
        ),
    ]
