# Generated by Django 6.0.2 on 2026-03-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrophotography", "0015_alter_astroimage_original_image_and_more"),
        ("core", "0003_alter_landingpagesettings_serve_webp_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpagesettings",
            name="latest_filters",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags that will appear as filters in the 'Latest images' section.",
                to="astrophotography.tag",
                verbose_name="Latest Image Filters",
            ),
        ),
    ]
