# Generated by Django 6.0.1 on 2026-01-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_landingpagesettings_location_slider_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpagesettings",
            name="meteors_enabled",
            field=models.BooleanField(default=True, verbose_name="Meteors Enabled"),
        ),
    ]
