# Generated by Django 6.0.3 on 2026-04-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_landingpagesettings_latest_filters"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpagesettings",
            name="shop_enabled",
            field=models.BooleanField(default=False, verbose_name="Shop Section Enabled"),
        ),
    ]
