# Generated by Django 6.0.5 on 2026-06-20 21:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0005_landingpagesettings_shop_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Stable identifier of this generated image variant row.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        help_text="Primary key of the concrete image object that owns this variant."
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        editable=False,
                        help_text="Generated WebP file stored for this variant.",
                        upload_to="",
                        verbose_name="File",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Frontend display role for this variant, such as card, detail, or hero.",
                        max_length=32,
                        verbose_name="Role",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        help_text="Generated image width in pixels.", verbose_name="Width"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        help_text="Generated image height in pixels.", verbose_name="Height"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        default="image/webp",
                        help_text="MIME type of the generated variant file.",
                        max_length=64,
                        verbose_name="MIME Type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this variant row was first created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this variant row was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Concrete image model that owns this variant.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["role", "width"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="core_imagev_content_37cdc4_idx"
                    ),
                    models.Index(fields=["role", "width"], name="core_imagev_role_b0fe3a_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "role", "width"),
                        name="core_imagevariant_unique_owner_role_width",
                    )
                ],
            },
        ),
    ]
