# Generated by Codex to realign ImageVariant.object_id with current model type.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0006_imagevariant")]

    operations = [
        migrations.AlterField(
            model_name="imagevariant",
            name="object_id",
            field=models.CharField(
                max_length=64,
                help_text="Primary key of the concrete image object that owns this variant.",
            ),
        ),
    ]
