# Generated by Django 6.0.5 on 2026-06-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_imagevariant_object_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="serve_webp_images",
        ),
        migrations.AlterField(
            model_name="imagevariant",
            name="file",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Generated WebP file stored for this variant.",
                upload_to="",
                verbose_name="File",
            ),
        ),
    ]
